"""empty message

Revision ID: 00b0dc7e4ed7
Revises: a7cd560b5c94
Create Date: 2020-03-01 21:28:12.406317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00b0dc7e4ed7'
down_revision = 'a7cd560b5c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Project', sa.Column('herkomst', sa.Text(), nullable=True))
    op.drop_column('Def_Project', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_observation_location', 'observation', ['location'], unique=False)
    op.add_column('Def_Project', sa.Column('_id', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=True))
    op.create_index('idx_Def_Project_location', 'Def_Project', ['location'], unique=False)
    op.drop_column('Def_Project', 'herkomst')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
