"""empty message

Revision ID: 034282803550
Revises: ccadce54b991
Create Date: 2020-03-08 20:13:52.428521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034282803550'
down_revision = 'ccadce54b991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('origine', sa.String(length=40), nullable=True))
    op.add_column('Def_Artefact', sa.Column('typecd', sa.String(length=40), nullable=True))
    op.drop_column('Def_Artefact', 'projectcd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('projectcd', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_column('Def_Artefact', 'typecd')
    op.drop_column('Def_Artefact', 'origine')
    # ### end Alembic commands ###
