"""Nog meer overbodige velden verwijderd

Revision ID: 0599f76be1ee
Revises: e7a45c0787e0
Create Date: 2022-02-04 13:57:14.665592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0599f76be1ee'
down_revision = 'e7a45c0787e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wasstraat_model')
    op.drop_column('Def_Plaatsing', 'table')
    op.drop_column('Def_Plaatsing', 'herkomst.0')
    op.drop_column('Def_Standplaats', 'herkomst.0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Standplaats', sa.Column('herkomst.0', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Def_Plaatsing', sa.Column('herkomst.0', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Def_Plaatsing', sa.Column('table', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.create_table('wasstraat_model',
    sa.Column('herkomst', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('soort', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('brondata', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
