"""Put verbeterd

Revision ID: 0688497336ab
Revises: 142f8c99f1c6
Create Date: 2022-02-16 13:51:44.543677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0688497336ab'
down_revision = '142f8c99f1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('Def_Doos', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('Def_Foto', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('Def_Plaatsing', sa.Column('key', sa.Text(), nullable=True))
    op.drop_index('idx_Def_Project_location', table_name='Def_Project')
    op.add_column('Def_Put', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('Def_Put', sa.Column('beschrijving', sa.Text(), nullable=True))
    op.add_column('Def_Put', sa.Column('aangelegd', sa.Boolean(), nullable=True))
    op.add_column('Def_Put', sa.Column('datum_ingevoerd', sa.Text(), nullable=True))
    op.add_column('Def_Put', sa.Column('datum_gewijzigd', sa.Text(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('Def_Standplaats', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('Def_Stelling', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('Def_Vindplaats', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('Def_Vlak', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('Def_Vondst', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('contact', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('contact_group', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('gender', sa.Column('key', sa.Text(), nullable=True))
    op.add_column('observation', sa.Column('key', sa.Text(), nullable=True))
    op.drop_index('idx_observation_location', table_name='observation')
    op.add_column('person', sa.Column('key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'key')
    op.create_index('idx_observation_location', 'observation', ['location'], unique=False)
    op.drop_column('observation', 'key')
    op.drop_column('gender', 'key')
    op.drop_column('contact_group', 'key')
    op.drop_column('contact', 'key')
    op.drop_column('Def_Vondst', 'key')
    op.drop_column('Def_Vlak', 'key')
    op.drop_column('Def_Vindplaats', 'key')
    op.drop_column('Def_Stelling', 'key')
    op.drop_column('Def_Standplaats', 'key')
    op.drop_column('Def_Spoor', 'key')
    op.drop_column('Def_Put', 'datum_gewijzigd')
    op.drop_column('Def_Put', 'datum_ingevoerd')
    op.drop_column('Def_Put', 'aangelegd')
    op.drop_column('Def_Put', 'beschrijving')
    op.drop_column('Def_Put', 'key')
    op.create_index('idx_Def_Project_location', 'Def_Project', ['location'], unique=False)
    op.drop_column('Def_Plaatsing', 'key')
    op.drop_column('Def_Foto', 'key')
    op.drop_column('Def_Doos', 'key')
    op.drop_column('Def_Artefact', 'key')
    # ### end Alembic commands ###
