"""Vondst verbeterd

Revision ID: 08188ed2e4a2
Revises: 67478736bf39
Create Date: 2022-02-16 15:06:03.431263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08188ed2e4a2'
down_revision = '67478736bf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vondst', sa.Column('segment', sa.String(length=200), nullable=True))
    op.add_column('Def_Vondst', sa.Column('vaknummer', sa.String(length=200), nullable=True))
    op.add_column('Def_Vondst', sa.Column('verzamelwijze', sa.String(length=200), nullable=True))
    op.add_column('Def_Vondst', sa.Column('vullingnr', sa.String(length=200), nullable=True))
    op.add_column('Def_Vondst', sa.Column('spoorID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Vondst_spoorID'), 'Def_Vondst', ['spoorID'], unique=False)
    op.drop_constraint('Def_Vondst_projectID_fkey', 'Def_Vondst', type_='foreignkey')
    op.drop_constraint('Def_Vondst_putID_fkey', 'Def_Vondst', type_='foreignkey')
    op.create_foreign_key(None, 'Def_Vondst', 'Def_Spoor', ['spoorID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Vondst', 'Def_Project', ['projectID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Vondst', 'Def_Put', ['putID'], ['primary_key'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Vondst', type_='foreignkey')
    op.drop_constraint(None, 'Def_Vondst', type_='foreignkey')
    op.drop_constraint(None, 'Def_Vondst', type_='foreignkey')
    op.create_foreign_key('Def_Vondst_putID_fkey', 'Def_Vondst', 'Def_Put', ['putID'], ['primary_key'])
    op.create_foreign_key('Def_Vondst_projectID_fkey', 'Def_Vondst', 'Def_Project', ['projectID'], ['primary_key'])
    op.drop_index(op.f('ix_Def_Vondst_spoorID'), table_name='Def_Vondst')
    op.drop_column('Def_Vondst', 'spoorID')
    op.drop_column('Def_Vondst', 'vullingnr')
    op.drop_column('Def_Vondst', 'verzamelwijze')
    op.drop_column('Def_Vondst', 'vaknummer')
    op.drop_column('Def_Vondst', 'segment')
    # ### end Alembic commands ###
