"""ABR-coderig toegevoegd 2

Revision ID: 0a8396bfa25d
Revises: f5e2d9e9c13e
Create Date: 2022-10-22 14:27:09.026934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8396bfa25d'
down_revision = 'f5e2d9e9c13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_ABR', sa.Column('uris', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_ABR', 'uris')
    # ### end Alembic commands ###
