"""Aantal artefacten toegevoegd aan Project

Revision ID: 0ce6fa103a35
Revises: 84b2e722a04c
Create Date: 2022-06-08 14:24:54.228117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce6fa103a35'
down_revision = '84b2e722a04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Project', sa.Column('aantal_artefacten', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Project', 'aantal_artefacten')
    # ### end Alembic commands ###
