"""empty message

Revision ID: 138257b5d9eb
Revises: 6e187e33454b
Create Date: 2020-03-08 21:07:29.759889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138257b5d9eb'
down_revision = '6e187e33454b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print()
    # ### end Alembic commands ###
