"""Spoor uitgebreid

Revision ID: 142f8c99f1c6
Revises: b3259e91bb5a
Create Date: 2022-02-04 14:26:46.679278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142f8c99f1c6'
down_revision = 'b3259e91bb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('aard', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('beschrijving', sa.Text(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('dateringvanaf', sa.Integer(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('dateringtot', sa.Integer(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('datering', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('vorm', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('diepte', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Spoor', 'diepte')
    op.drop_column('Def_Spoor', 'vorm')
    op.drop_column('Def_Spoor', 'datering')
    op.drop_column('Def_Spoor', 'dateringtot')
    op.drop_column('Def_Spoor', 'dateringvanaf')
    op.drop_column('Def_Spoor', 'beschrijving')
    op.drop_column('Def_Spoor', 'aard')
    # ### end Alembic commands ###
