"""Fotovelden goed gezet 2

Revision ID: 178dc966877a
Revises: 1b4afa918ddc
Create Date: 2022-05-05 09:35:21.325174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178dc966877a'
down_revision = '1b4afa918ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Foto', sa.Column('subnr', sa.Integer(), nullable=True))
    op.drop_column('Def_Foto', 'artefactnr')
    op.drop_column('Def_Foto', 'fotosubnr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Foto', sa.Column('fotosubnr', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Def_Foto', sa.Column('artefactnr', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('Def_Foto', 'subnr')
    # ### end Alembic commands ###
