"""Fotovelden goed gezet

Revision ID: 1b4afa918ddc
Revises: 6a50d8ff3c77
Create Date: 2022-05-05 09:12:55.653322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4afa918ddc'
down_revision = '6a50d8ff3c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Foto', 'fotonr',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='fotonr::numeric')
    op.alter_column('Def_Foto', 'fotosubnr',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='fotosubnr::numeric')
    op.alter_column('Def_Foto', 'putnr',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='putnr::numeric')
    op.alter_column('Def_Foto', 'vondstnr',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='vondstnr::numeric')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Foto', 'vondstnr',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'putnr',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'fotosubnr',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'fotonr',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
