"""empty message

Revision ID: 1fc38b4855da
Revises: 7ebf557eddc6
Create Date: 2020-02-23 23:02:13.889745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc38b4855da'
down_revision = '7ebf557eddc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Project', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('Def_Project', sa.Column('longitute', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Project', 'longitute')
    op.drop_column('Def_Project', 'latitude')
    # ### end Alembic commands ###
