"""Polymorph Aartdewerk toegevoegd

Revision ID: 2491a0b1ac48
Revises: 1166e7ca1510
Create Date: 2022-02-28 20:58:48.823668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2491a0b1ac48'
down_revision = '1166e7ca1510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('baksel', sa.String(length=200), nullable=True, comment='soort AW'))
    op.add_column('Def_Artefact', sa.Column('bakseltype', sa.String(length=200), nullable=True, comment='bakseltype'))
    op.add_column('Def_Artefact', sa.Column('bodem', sa.String(length=200), nullable=True, comment='vorm van de bodem/voet'))
    op.add_column('Def_Artefact', sa.Column('categorie', sa.String(length=200), nullable=True, comment='categorie'))
    op.add_column('Def_Artefact', sa.Column('codes', sa.String(length=200), nullable=True, comment='codes van type'))
    op.add_column('Def_Artefact', sa.Column('decoratie', sa.String(length=200), nullable=True, comment='decoratie'))
    op.add_column('Def_Artefact', sa.Column('diameter', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('fragment', sa.String(length=200), nullable=True, comment='fragment: rand, wand, bodem, oor etc'))
    op.add_column('Def_Artefact', sa.Column('glazuur', sa.String(length=200), nullable=True, comment='glazuur'))
    op.add_column('Def_Artefact', sa.Column('grootste_diameter', sa.String(length=200), nullable=True, comment='grootste diameter in millimeters, 0 = niet gemeten'))
    op.add_column('Def_Artefact', sa.Column('hoogte', sa.String(length=200), nullable=True, comment='hoogte in millimeters, 0 = niet gemeten'))
    op.add_column('Def_Artefact', sa.Column('kleur', sa.String(length=200), nullable=True, comment='kleur'))
    op.add_column('Def_Artefact', sa.Column('materiaalsoort', sa.String(length=200), nullable=True, comment='materiaalsoort'))
    op.add_column('Def_Artefact', sa.Column('max_diameter', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('oor', sa.String(length=200), nullable=True, comment='vorm en versiering van oor'))
    op.add_column('Def_Artefact', sa.Column('past_aan', sa.String(length=200), nullable=True, comment='vondstnummer waar scherf aan past'))
    op.add_column('Def_Artefact', sa.Column('percentage', sa.String(length=200), nullable=True, comment='aanwezig percentage van een pot'))
    op.add_column('Def_Artefact', sa.Column('productiewijze', sa.String(length=200), nullable=True, comment='produktiewijze'))
    op.add_column('Def_Artefact', sa.Column('rand', sa.String(length=200), nullable=True, comment='vorm en versiering van rand'))
    op.add_column('Def_Artefact', sa.Column('rand_bodem', sa.String(length=200), nullable=True, comment='diameter bodem in millimeters, 0 = niet gemeten'))
    op.add_column('Def_Artefact', sa.Column('rand_diameter', sa.String(length=200), nullable=True, comment='diameter rand in millimeters, 0 = niet gemeten'))
    op.add_column('Def_Artefact', sa.Column('vorm', sa.String(length=200), nullable=True, comment='vorm'))
    op.alter_column('Def_Artefact', 'materiaal',
               existing_type=sa.VARCHAR(length=200),
               comment='materiaal',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Artefact', 'materiaal',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='materiaal',
               existing_nullable=True)
    op.drop_column('Def_Artefact', 'vorm')
    op.drop_column('Def_Artefact', 'rand_diameter')
    op.drop_column('Def_Artefact', 'rand_bodem')
    op.drop_column('Def_Artefact', 'rand')
    op.drop_column('Def_Artefact', 'productiewijze')
    op.drop_column('Def_Artefact', 'percentage')
    op.drop_column('Def_Artefact', 'past_aan')
    op.drop_column('Def_Artefact', 'oor')
    op.drop_column('Def_Artefact', 'max_diameter')
    op.drop_column('Def_Artefact', 'materiaalsoort')
    op.drop_column('Def_Artefact', 'kleur')
    op.drop_column('Def_Artefact', 'hoogte')
    op.drop_column('Def_Artefact', 'grootste_diameter')
    op.drop_column('Def_Artefact', 'glazuur')
    op.drop_column('Def_Artefact', 'fragment')
    op.drop_column('Def_Artefact', 'diameter')
    op.drop_column('Def_Artefact', 'decoratie')
    op.drop_column('Def_Artefact', 'codes')
    op.drop_column('Def_Artefact', 'categorie')
    op.drop_column('Def_Artefact', 'bodem')
    op.drop_column('Def_Artefact', 'bakseltype')
    op.drop_column('Def_Artefact', 'baksel')
    # ### end Alembic commands ###
