"""empty message

Revision ID: 2a5f715a7eac
Revises: fc8b97821ac8
Create Date: 2023-03-22 15:10:24.999755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5f715a7eac'
down_revision = 'fc8b97821ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_Artefact', schema=None) as batch_op:
        batch_op.alter_column('max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)

    with op.batch_alter_table('Def_Monster_Botanie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soort_botanie', sa.String(length=80), nullable=True))

    with op.batch_alter_table('Def_Monster_Schelp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soort_schelp', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_Monster_Schelp', schema=None) as batch_op:
        batch_op.drop_column('soort_schelp')

    with op.batch_alter_table('Def_Monster_Botanie', schema=None) as batch_op:
        batch_op.drop_column('soort_botanie')

    with op.batch_alter_table('Def_Artefact', schema=None) as batch_op:
        batch_op.alter_column('wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)

    # ### end Alembic commands ###
