"""Better index

Revision ID: 2c03f392bfe3
Revises: c09f6d00d6a2
Create Date: 2022-05-20 10:10:44.198458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c03f392bfe3'
down_revision = 'c09f6d00d6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Foto_fototype_fileName', 'Def_Foto', ['fototype', 'fileName'], unique=False)
    op.drop_index('idx_Def_Project_location', table_name='Def_Project')
    op.drop_index('ix_Def_Vondst_nieuw', table_name='Def_Vondst')
    op.drop_column('Def_Vondst', 'nieuw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vondst', sa.Column('nieuw', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.create_index('ix_Def_Vondst_nieuw', 'Def_Vondst', ['nieuw'], unique=False)
    op.create_index('idx_Def_Project_location', 'Def_Project', ['location'], unique=False)
    op.drop_index('ix_Foto_fototype_fileName', table_name='Def_Foto')
    # ### end Alembic commands ###
