"""empty message

Revision ID: 30bcd87e1b65
Revises: 2c03f392bfe3
Create Date: 2022-06-08 08:56:07.373509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bcd87e1b65'
down_revision = '2c03f392bfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('foto_teller', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Artefact', 'foto_teller')
    # ### end Alembic commands ###
