"""empty message

Revision ID: 334b4b97b356
Revises: 8eebd53c40aa
Create Date: 2020-03-02 21:24:31.334387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334b4b97b356'
down_revision = '8eebd53c40aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Fotos', 'photo')
    op.drop_column('person', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Def_Fotos', sa.Column('photo', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
