"""Koppeling naar ABR-tabel

Revision ID: 3879b13b609f
Revises: 0a8396bfa25d
Create Date: 2022-10-24 20:01:09.790198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3879b13b609f'
down_revision = '0a8396bfa25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('abr_materiaal_id', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('sub_abr_materiaal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Artefact_abr_materiaal_id'), 'Def_Artefact', ['abr_materiaal_id'], unique=False)
    op.create_index(op.f('ix_Def_Artefact_sub_abr_materiaal_id'), 'Def_Artefact', ['sub_abr_materiaal_id'], unique=False)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_ABR', ['sub_abr_materiaal_id'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_ABR', ['abr_materiaal_id'], ['primary_key'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Artefact_sub_abr_materiaal_id'), table_name='Def_Artefact')
    op.drop_index(op.f('ix_Def_Artefact_abr_materiaal_id'), table_name='Def_Artefact')
    op.drop_column('Def_Artefact', 'sub_abr_materiaal_id')
    op.drop_column('Def_Artefact', 'abr_materiaal_id')
    # ### end Alembic commands ###
