"""Tekening attributen

Revision ID: 3ace0e960948
Revises: cb226401b07d
Create Date: 2022-08-31 11:03:00.549173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ace0e960948'
down_revision = 'cb226401b07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Foto', sa.Column('putID', sa.Integer(), nullable=True))
    op.add_column('Def_Foto', sa.Column('spoorID', sa.Integer(), nullable=True))
    op.add_column('Def_Foto', sa.Column('vondstID', sa.Integer(), nullable=True))
    op.add_column('Def_Foto', sa.Column('coupe', sa.Boolean(), nullable=True))
    op.add_column('Def_Foto', sa.Column('details', sa.String(length=1024), nullable=True))
    op.add_column('Def_Foto', sa.Column('microfilm', sa.String(length=1024), nullable=True))
    op.add_column('Def_Foto', sa.Column('periode', sa.String(length=1024), nullable=True))
    op.add_column('Def_Foto', sa.Column('profiel', sa.String(length=1024), nullable=True))
    op.add_column('Def_Foto', sa.Column('schaal', sa.Integer(), nullable=True))
    op.add_column('Def_Foto', sa.Column('volgnr', sa.Integer(), nullable=True))
    op.alter_column('Def_Foto', 'soort',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.create_index(op.f('ix_Def_Foto_putID'), 'Def_Foto', ['putID'], unique=False)
    op.create_index(op.f('ix_Def_Foto_spoorID'), 'Def_Foto', ['spoorID'], unique=False)
    op.create_index(op.f('ix_Def_Foto_vondstID'), 'Def_Foto', ['vondstID'], unique=False)
    op.create_foreign_key(None, 'Def_Foto', 'Def_Put', ['putID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Foto', 'Def_Spoor', ['spoorID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Foto', 'Def_Vondst', ['vondstID'], ['primary_key'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Foto', type_='foreignkey')
    op.drop_constraint(None, 'Def_Foto', type_='foreignkey')
    op.drop_constraint(None, 'Def_Foto', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Foto_vondstID'), table_name='Def_Foto')
    op.drop_index(op.f('ix_Def_Foto_spoorID'), table_name='Def_Foto')
    op.drop_index(op.f('ix_Def_Foto_putID'), table_name='Def_Foto')
    op.alter_column('Def_Foto', 'soort',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.drop_column('Def_Foto', 'volgnr')
    op.drop_column('Def_Foto', 'schaal')
    op.drop_column('Def_Foto', 'profiel')
    op.drop_column('Def_Foto', 'periode')
    op.drop_column('Def_Foto', 'microfilm')
    op.drop_column('Def_Foto', 'details')
    op.drop_column('Def_Foto', 'coupe')
    op.drop_column('Def_Foto', 'vondstID')
    op.drop_column('Def_Foto', 'spoorID')
    op.drop_column('Def_Foto', 'putID')
    # ### end Alembic commands ###
