"""Bruiklenen toegevoegd 4

Revision ID: 3cde970b04b1
Revises: cf658131cb2f
Create Date: 2022-11-25 08:08:30.613590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cde970b04b1'
down_revision = 'cf658131cb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.add_column('Def_Bruikleen', sa.Column('projectID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Bruikleen_projectID'), 'Def_Bruikleen', ['projectID'], unique=False)
    op.create_foreign_key(None, 'Def_Bruikleen', 'Def_Project', ['projectID'], ['primary_key'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Bruikleen', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Bruikleen_projectID'), table_name='Def_Bruikleen')
    op.drop_column('Def_Bruikleen', 'projectID')
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
