"""empty message

Revision ID: 3d1c7ffc3946
Revises: e18e341cd2fb
Create Date: 2020-03-09 21:12:48.231464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1c7ffc3946'
down_revision = 'e18e341cd2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('putID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Artefact_putID'), 'Def_Artefact', ['putID'], unique=False)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Put', ['putID'], ['primary_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Artefact_putID'), table_name='Def_Artefact')
    op.drop_column('Def_Artefact', 'putID')
    # ### end Alembic commands ###
