"""ABRLink verwijderd

Revision ID: 3ecf71189c13
Revises: cf10deba8f31
Create Date: 2022-11-18 14:15:46.649538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ecf71189c13'
down_revision = 'cf10deba8f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Def_ABRLink_abr_materiaal_id', table_name='Def_ABRLink')
    op.drop_index('ix_Def_ABRLink_artefactsoort', table_name='Def_ABRLink')
    op.drop_index('ix_Def_Artefact_abrlink_id', table_name='Def_Artefact')
    op.drop_constraint('Def_Artefact_abrlink_id_fkey', 'Def_Artefact', type_='foreignkey')
    op.drop_column('Def_Artefact', 'abrlink_id')
    op.drop_table('Def_ABRLink')

    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Def_ABRLink',
        sa.Column('artefactsoort', postgresql.ENUM('Aardewerk', 'Dierlijk_Bot', 'Glas', 'Hout', 'Bouwaardewerk', 'Kleipijp', 'Leer', 'Menselijk_Bot', 'Metaal', 'Munt', 'Onbekend', 'Schelp', 'Steen', 'Textiel', name='discrartefactsoortenum'), autoincrement=False, nullable=False),
        sa.Column('abr_materiaal_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['abr_materiaal_id'], ['Def_ABR.primary_key'], name='Def_ABRLink_abr_materiaal_id_fkey', deferrable=True),
        sa.PrimaryKeyConstraint('artefactsoort', name='Def_ABRLink_pkey')
    )
    op.create_index('ix_Def_ABRLink_artefactsoort', 'Def_ABRLink', ['artefactsoort'], unique=False)
    op.create_index('ix_Def_ABRLink_abr_materiaal_id', 'Def_ABRLink', ['abr_materiaal_id'], unique=False)
    op.add_column('Def_Artefact', sa.Column('abrlink_id', postgresql.ENUM('Aardewerk', 'Dierlijk_Bot', 'Glas', 'Hout', 'Bouwaardewerk', 'Kleipijp', 'Leer', 'Menselijk_Bot', 'Metaal', 'Munt', 'Onbekend', 'Schelp', 'Steen', 'Textiel', name='discrartefactsoortenum'), autoincrement=False, nullable=True))
    op.create_foreign_key('Def_Artefact_abrlink_id_fkey', 'Def_Artefact', 'Def_ABRLink', ['abrlink_id'], ['artefactsoort'], deferrable=True)
    op.create_index('ix_Def_Artefact_abrlink_id', 'Def_Artefact', ['abrlink_id'], unique=False)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
