"""Artefact uitgebreid Diversen

Revision ID: 43491a7a32b5
Revises: 457369173800
Create Date: 2022-02-28 21:25:42.914042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43491a7a32b5'
down_revision = '457369173800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('C14_datering', sa.String(length=200), nullable=True, comment='C14 datering mogelijk ja of nee'))
    op.add_column('Def_Artefact', sa.Column('dendrodatering', sa.String(length=200), nullable=True, comment='dendrodatering mogelijk ja of nee'))
    op.add_column('Def_Artefact', sa.Column('determinatieniveau', sa.String(length=200), nullable=True, comment='het determinatieniveau; bv. cf. = onzekere determinatie'))
    op.add_column('Def_Artefact', sa.Column('gebruikssporen', sa.String(length=200), nullable=True, comment='gebruikssporen'))
    op.add_column('Def_Artefact', sa.Column('houtsoort', sa.String(length=200), nullable=True, comment='code voor de houtsoort'))
    op.add_column('Def_Artefact', sa.Column('houtsoortcd', sa.String(length=200), nullable=True, comment='code voor de houtsoort'))
    op.add_column('Def_Artefact', sa.Column('jaarring_bast_spint', sa.String(length=200), nullable=True, comment='jaarring, spint, bast'))
    op.add_column('Def_Artefact', sa.Column('puntlengte', sa.String(length=200), nullable=True, comment='puntlengte : de lengte  in cm van de punt gemeten van hoogste kapvlak'))
    op.add_column('Def_Artefact', sa.Column('puntvorm', sa.String(length=200), nullable=True, comment='puntvorm : het aantal vlakken waarmee de punt is gemaakt halverwege de punt'))
    op.add_column('Def_Artefact', sa.Column('stamcode', sa.String(length=200), nullable=True, comment='stamcode : 0 =onbekend'))
    op.add_column('Def_Artefact', sa.Column('gedraaid', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('handgevormd', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('magering', sa.String(length=200), nullable=True, comment='magering'))
    op.add_column('Def_Artefact', sa.Column('maker', sa.String(length=200), nullable=True, comment='Maker (vnl. i.g.v. kleipijpen)'))
    op.add_column('Def_Artefact', sa.Column('oor_steel', sa.String(length=200), nullable=True, comment='Oor steel'))
    op.add_column('Def_Artefact', sa.Column('oppervlakte', sa.String(length=200), nullable=True, comment='oppervlakte behandeling'))
    op.add_column('Def_Artefact', sa.Column('randdiameter', sa.String(length=200), nullable=True, comment='Randdiameter in cm'))
    op.add_column('Def_Artefact', sa.Column('randindex', sa.String(length=200), nullable=True, comment='Randindex (RANDPER / 100)'))
    op.add_column('Def_Artefact', sa.Column('randpercentage', sa.String(length=200), nullable=True, comment='Randpercentage'))
    op.add_column('Def_Artefact', sa.Column('subbaksel', sa.String(length=200), nullable=True, comment='Subbaksel'))
    op.add_column('Def_Artefact', sa.Column('type_rand', sa.String(length=200), nullable=True, comment='type rand'))
    op.add_column('Def_Artefact', sa.Column('wanddikte', sa.String(length=200), nullable=True, comment='wanddikte'))
    op.add_column('Def_Artefact', sa.Column('beschrijving_zool', sa.String(length=200), nullable=True, comment='Verder beschrijving van de zool'))
    op.add_column('Def_Artefact', sa.Column('bewerking', sa.String(length=200), nullable=True, comment='bewerking'))
    op.add_column('Def_Artefact', sa.Column('bewerkinssporen', sa.String(length=200), nullable=True, comment='Bewerkinssporen'))
    op.add_column('Def_Artefact', sa.Column('bovenleer', sa.String(length=200), nullable=True, comment='bovenleer: bv. wreef, hiel, tong, etc.'))
    op.add_column('Def_Artefact', sa.Column('kwaliteit', sa.String(length=200), nullable=True, comment='numismatische kwaliteitsaanduiding : goed, f.d.c.'))
    op.add_column('Def_Artefact', sa.Column('leersoort', sa.String(length=200), nullable=True, comment='Leersoort (Naam dier)'))
    op.add_column('Def_Artefact', sa.Column('sluiting', sa.String(length=200), nullable=True, comment='sluiting: bv. veter, gesp, riem, etc.'))
    op.add_column('Def_Artefact', sa.Column('soort_sluiting', sa.String(length=200), nullable=True, comment='Soort sluiting'))
    op.add_column('Def_Artefact', sa.Column('toestand', sa.String(length=200), nullable=True, comment='toestand: nat of droog'))
    op.add_column('Def_Artefact', sa.Column('type_bovenleer', sa.String(length=200), nullable=True, comment='Type bovenleer'))
    op.add_column('Def_Artefact', sa.Column('verbinding', sa.String(length=200), nullable=True, comment='verbinding tussen zool en bovenleer'))
    op.add_column('Def_Artefact', sa.Column('zool', sa.String(length=200), nullable=True, comment='zool: dubbel, enkel, etc.'))
    op.add_column('Def_Artefact', sa.Column('zoolvorm', sa.String(length=200), nullable=True, comment='zoolvorm: code volgens Goubitz, Stepping through time (bladzijde 82)'))
    op.add_column('Def_Artefact', sa.Column('breedte_kist_hoofdeinde', sa.String(length=200), nullable=True, comment='in cm'))
    op.add_column('Def_Artefact', sa.Column('breedte_kist_voeteinde', sa.String(length=200), nullable=True, comment='in cm'))
    op.add_column('Def_Artefact', sa.Column('doos_delft', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('doos_lumc', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('kist_waargenomen', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('lengte_kist', sa.String(length=200), nullable=True, comment='in cm'))
    op.add_column('Def_Artefact', sa.Column('linkerarm', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('linkerbeen', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('plaats', sa.String(length=200), nullable=True, comment='plaats van bewaring'))
    op.add_column('Def_Artefact', sa.Column('primair_graf', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('rechterarm', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('rechterbeen', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('schedel', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('secundair_graf', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('skeletelementen', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('wervelkolom', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('diverse', sa.String(length=200), nullable=True, comment='diverse: aangetast, licht aangetast, zwaar aangetast en/of geirriseerd'))
    op.add_column('Def_Artefact', sa.Column('metaalsoort', sa.String(length=200), nullable=True, comment='Metaal soort'))
    op.add_column('Def_Artefact', sa.Column('oppervlak', sa.String(length=200), nullable=True, comment='oppervlak'))
    op.add_column('Def_Artefact', sa.Column('aard_verwerving', sa.String(length=200), nullable=True, comment='koop, schenking, legaat, bruikleen etc.'))
    op.add_column('Def_Artefact', sa.Column('autoriteit', sa.String(length=200), nullable=True, comment='naam van vorst (met jaartallen), instantie, opdrachtgever'))
    op.add_column('Def_Artefact', sa.Column('conditie', sa.String(length=200), nullable=True, comment='alleen invullen in uitzonderlijke situatie, restauratie nodig ?'))
    op.add_column('Def_Artefact', sa.Column('eenheid', sa.String(length=200), nullable=True, comment='bv : kwart, halve, dubbele, 1, 10, 25'))
    op.add_column('Def_Artefact', sa.Column('gelegenheid', sa.String(length=200), nullable=True, comment='korte aanduiding'))
    op.add_column('Def_Artefact', sa.Column('inventaris', sa.String(length=200), nullable=True, comment='huidig inventarisnummer (eventueel oude inv. nrs)'))
    op.add_column('Def_Artefact', sa.Column('jaartal', sa.String(length=200), nullable=True, comment='jaartal op voorwerp (of periode)'))
    op.add_column('Def_Artefact', sa.Column('keerzijde_tekst', sa.String(length=200), nullable=True, comment='volledige teks'))
    op.add_column('Def_Artefact', sa.Column('land', sa.String(length=200), nullable=True, comment='land van uitgifte (politieke eenheid)'))
    op.add_column('Def_Artefact', sa.Column('muntplaats', sa.String(length=200), nullable=True, comment='plaats van aanmunting'))
    op.add_column('Def_Artefact', sa.Column('muntsoort', sa.String(length=200), nullable=True, comment='in enkelvoud, bv daalder, gulden, cent'))
    op.add_column('Def_Artefact', sa.Column('ontwerper', sa.String(length=200), nullable=True, comment='naam (met jaartallen)'))
    op.add_column('Def_Artefact', sa.Column('produktiewijze', sa.String(length=200), nullable=True, comment='alleen invullen indien nodig'))
    op.add_column('Def_Artefact', sa.Column('randafwerking', sa.String(length=200), nullable=True, comment='alleen invullen indien niet glad'))
    op.add_column('Def_Artefact', sa.Column('randschrift', sa.String(length=200), nullable=True, comment='volldedige tekst'))
    op.add_column('Def_Artefact', sa.Column('rubriek', sa.String(length=200), nullable=True, comment='grove indeling in gebied, periode of politieke eenheid'))
    op.add_column('Def_Artefact', sa.Column('signalement', sa.String(length=200), nullable=True, comment='korte beschrijving, signalement'))
    op.add_column('Def_Artefact', sa.Column('verworven_van', sa.String(length=200), nullable=True, comment='verworven van wie en wanneer'))
    op.add_column('Def_Artefact', sa.Column('vindplaats', sa.String(length=200), nullable=True, comment='allleen voor(bodem)vondsten, waar en wanneer'))
    op.add_column('Def_Artefact', sa.Column('voorwaarden_verwerving', sa.String(length=200), nullable=True, comment='eventueel aan de verwerving verbonden voorwaarden'))
    op.add_column('Def_Artefact', sa.Column('voorzijde_tekst', sa.String(length=200), nullable=True, comment='volledige teks'))
    op.add_column('Def_Artefact', sa.Column('dikte', sa.String(length=200), nullable=True, comment='dikte in mm'))
    op.add_column('Def_Artefact', sa.Column('steengroep', sa.String(length=200), nullable=True, comment='Steengroep'))
    op.add_column('Def_Artefact', sa.Column('steensoort', sa.String(length=200), nullable=True, comment='steensoort'))
    op.add_column('Def_Artefact', sa.Column('subsoort', sa.String(length=200), nullable=True, comment='subsoort'))
    op.alter_column('Def_Artefact', 'materiaal',
               existing_type=sa.VARCHAR(length=200),
               comment='bv : goud, zilver',
               existing_comment='Materiaal',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'baksel',
               existing_type=sa.VARCHAR(length=200),
               comment='Baksel',
               existing_comment='soort AW',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bodem',
               existing_type=sa.VARCHAR(length=200),
               comment='Bodem',
               existing_comment='vorm van de bodem/voet',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diameter',
               existing_type=sa.VARCHAR(length=200),
               comment='diameter in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'glazuur',
               existing_type=sa.VARCHAR(length=200),
               comment='Glazuur',
               existing_comment='glazuur',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'grootste_diameter',
               existing_type=sa.VARCHAR(length=200),
               comment='Grootste diameter in cm',
               existing_comment='grootste diameter in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'hoogte',
               existing_type=sa.VARCHAR(length=200),
               comment='Hoogte van voorwerp',
               existing_comment='hoogte in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'materiaalsoort',
               existing_type=sa.VARCHAR(length=200),
               comment='',
               existing_comment='materiaalsoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=200),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'past_aan',
               existing_type=sa.VARCHAR(length=200),
               comment='past aan andere nummers:',
               existing_comment='Past aan',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=200),
               comment='',
               existing_comment='Percentage',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'productiewijze',
               existing_type=sa.VARCHAR(length=200),
               comment='Productie wijze',
               existing_comment='produktiewijze',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm',
               existing_type=sa.VARCHAR(length=200),
               comment='alleen invullen als voorwerp niet rond is',
               existing_comment='vorm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bewerkingssporen',
               existing_type=sa.VARCHAR(length=200),
               comment='bewerkingssporen',
               existing_comment='Bewerkingssporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diameter_bodem',
               existing_type=sa.VARCHAR(length=200),
               comment='Diameter van bodem',
               existing_comment='diameter bodem in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Artefact', 'diameter_bodem',
               existing_type=sa.VARCHAR(length=200),
               comment='diameter bodem in millimeters, 0 = niet gemeten',
               existing_comment='Diameter van bodem',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bewerkingssporen',
               existing_type=sa.VARCHAR(length=200),
               comment='Bewerkingssporen',
               existing_comment='bewerkingssporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm',
               existing_type=sa.VARCHAR(length=200),
               comment='vorm',
               existing_comment='alleen invullen als voorwerp niet rond is',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'productiewijze',
               existing_type=sa.VARCHAR(length=200),
               comment='produktiewijze',
               existing_comment='Productie wijze',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=200),
               comment='Percentage',
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'past_aan',
               existing_type=sa.VARCHAR(length=200),
               comment='Past aan',
               existing_comment='past aan andere nummers:',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'materiaalsoort',
               existing_type=sa.VARCHAR(length=200),
               comment='materiaalsoort',
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'hoogte',
               existing_type=sa.VARCHAR(length=200),
               comment='hoogte in millimeters, 0 = niet gemeten',
               existing_comment='Hoogte van voorwerp',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'grootste_diameter',
               existing_type=sa.VARCHAR(length=200),
               comment='grootste diameter in millimeters, 0 = niet gemeten',
               existing_comment='Grootste diameter in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'glazuur',
               existing_type=sa.VARCHAR(length=200),
               comment='glazuur',
               existing_comment='Glazuur',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diameter',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='diameter in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bodem',
               existing_type=sa.VARCHAR(length=200),
               comment='vorm van de bodem/voet',
               existing_comment='Bodem',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'baksel',
               existing_type=sa.VARCHAR(length=200),
               comment='soort AW',
               existing_comment='Baksel',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'materiaal',
               existing_type=sa.VARCHAR(length=200),
               comment='Materiaal',
               existing_comment='bv : goud, zilver',
               existing_nullable=True)
    op.drop_column('Def_Artefact', 'subsoort')
    op.drop_column('Def_Artefact', 'steensoort')
    op.drop_column('Def_Artefact', 'steengroep')
    op.drop_column('Def_Artefact', 'dikte')
    op.drop_column('Def_Artefact', 'voorzijde_tekst')
    op.drop_column('Def_Artefact', 'voorwaarden_verwerving')
    op.drop_column('Def_Artefact', 'vindplaats')
    op.drop_column('Def_Artefact', 'verworven_van')
    op.drop_column('Def_Artefact', 'signalement')
    op.drop_column('Def_Artefact', 'rubriek')
    op.drop_column('Def_Artefact', 'randschrift')
    op.drop_column('Def_Artefact', 'randafwerking')
    op.drop_column('Def_Artefact', 'produktiewijze')
    op.drop_column('Def_Artefact', 'ontwerper')
    op.drop_column('Def_Artefact', 'muntsoort')
    op.drop_column('Def_Artefact', 'muntplaats')
    op.drop_column('Def_Artefact', 'land')
    op.drop_column('Def_Artefact', 'keerzijde_tekst')
    op.drop_column('Def_Artefact', 'jaartal')
    op.drop_column('Def_Artefact', 'inventaris')
    op.drop_column('Def_Artefact', 'gelegenheid')
    op.drop_column('Def_Artefact', 'eenheid')
    op.drop_column('Def_Artefact', 'conditie')
    op.drop_column('Def_Artefact', 'autoriteit')
    op.drop_column('Def_Artefact', 'aard_verwerving')
    op.drop_column('Def_Artefact', 'oppervlak')
    op.drop_column('Def_Artefact', 'metaalsoort')
    op.drop_column('Def_Artefact', 'diverse')
    op.drop_column('Def_Artefact', 'wervelkolom')
    op.drop_column('Def_Artefact', 'skeletelementen')
    op.drop_column('Def_Artefact', 'secundair_graf')
    op.drop_column('Def_Artefact', 'schedel')
    op.drop_column('Def_Artefact', 'rechterbeen')
    op.drop_column('Def_Artefact', 'rechterarm')
    op.drop_column('Def_Artefact', 'primair_graf')
    op.drop_column('Def_Artefact', 'plaats')
    op.drop_column('Def_Artefact', 'linkerbeen')
    op.drop_column('Def_Artefact', 'linkerarm')
    op.drop_column('Def_Artefact', 'lengte_kist')
    op.drop_column('Def_Artefact', 'kist_waargenomen')
    op.drop_column('Def_Artefact', 'doos_lumc')
    op.drop_column('Def_Artefact', 'doos_delft')
    op.drop_column('Def_Artefact', 'breedte_kist_voeteinde')
    op.drop_column('Def_Artefact', 'breedte_kist_hoofdeinde')
    op.drop_column('Def_Artefact', 'zoolvorm')
    op.drop_column('Def_Artefact', 'zool')
    op.drop_column('Def_Artefact', 'verbinding')
    op.drop_column('Def_Artefact', 'type_bovenleer')
    op.drop_column('Def_Artefact', 'toestand')
    op.drop_column('Def_Artefact', 'soort_sluiting')
    op.drop_column('Def_Artefact', 'sluiting')
    op.drop_column('Def_Artefact', 'leersoort')
    op.drop_column('Def_Artefact', 'kwaliteit')
    op.drop_column('Def_Artefact', 'bovenleer')
    op.drop_column('Def_Artefact', 'bewerkinssporen')
    op.drop_column('Def_Artefact', 'bewerking')
    op.drop_column('Def_Artefact', 'beschrijving_zool')
    op.drop_column('Def_Artefact', 'wanddikte')
    op.drop_column('Def_Artefact', 'type_rand')
    op.drop_column('Def_Artefact', 'subbaksel')
    op.drop_column('Def_Artefact', 'randpercentage')
    op.drop_column('Def_Artefact', 'randindex')
    op.drop_column('Def_Artefact', 'randdiameter')
    op.drop_column('Def_Artefact', 'oppervlakte')
    op.drop_column('Def_Artefact', 'oor_steel')
    op.drop_column('Def_Artefact', 'maker')
    op.drop_column('Def_Artefact', 'magering')
    op.drop_column('Def_Artefact', 'handgevormd')
    op.drop_column('Def_Artefact', 'gedraaid')
    op.drop_column('Def_Artefact', 'stamcode')
    op.drop_column('Def_Artefact', 'puntvorm')
    op.drop_column('Def_Artefact', 'puntlengte')
    op.drop_column('Def_Artefact', 'jaarring_bast_spint')
    op.drop_column('Def_Artefact', 'houtsoortcd')
    op.drop_column('Def_Artefact', 'houtsoort')
    op.drop_column('Def_Artefact', 'gebruikssporen')
    op.drop_column('Def_Artefact', 'determinatieniveau')
    op.drop_column('Def_Artefact', 'dendrodatering')
    op.drop_column('Def_Artefact', 'C14_datering')
    # ### end Alembic commands ###
