"""empty message

Revision ID: 4c9ccfe07e74
Revises: c12bc4245027
Create Date: 2020-03-09 22:30:25.147599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9ccfe07e74'
down_revision = 'c12bc4245027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vondst', sa.Column('_id', sa.String(length=40), nullable=False))
    op.add_column('Def_Vondst', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('Def_Vondst', sa.Column('herkomst', sa.String(length=200), nullable=True))
    op.add_column('Def_Vondst', sa.Column('key', sa.String(length=40), nullable=True))
    op.add_column('Def_Vondst', sa.Column('key_project', sa.String(length=40), nullable=True))
    op.add_column('Def_Vondst', sa.Column('key_put', sa.String(length=40), nullable=True))
    op.add_column('Def_Vondst', sa.Column('key_vlak', sa.String(length=40), nullable=True))
    op.create_unique_constraint(None, 'Def_Vondst', ['_id'])
    op.drop_column('Def_Vondst', 'putnr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vondst', sa.Column('putnr', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Def_Vondst', type_='unique')
    op.drop_column('Def_Vondst', 'key_vlak')
    op.drop_column('Def_Vondst', 'key_put')
    op.drop_column('Def_Vondst', 'key_project')
    op.drop_column('Def_Vondst', 'key')
    op.drop_column('Def_Vondst', 'herkomst')
    op.drop_column('Def_Vondst', 'brondata')
    op.drop_column('Def_Vondst', '_id')
    # ### end Alembic commands ###
