"""Default String length naar 320

Revision ID: 5004dfbf5c1e
Revises: 8b9fac6fe537
Create Date: 2022-03-06 21:15:29.400423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5004dfbf5c1e'
down_revision = '8b9fac6fe537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Artefact', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'typevoorwerp',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'typecd',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'functievoorwerp',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'origine',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'datering',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'literatuur',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'ABRcodering',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'afmetingen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'catalogus',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'compleetheid',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gewicht',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'groep',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'mai',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='MAI, minimum aantal individuen, 0 = onbekend, meer dan 1',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'formaat_horizontaal',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'formaat_vericaal',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'materiaal',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='bv : goud, zilver',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'naam_voorwerp',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'plek',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'publicatiecode',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'typenaam',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'versiering',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vondstomstandigheden',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'baksel',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Baksel',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bakseltype',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='bakseltype',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bodem',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Bodem',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'categorie',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='categorie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'codes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='codes van type',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'decoratie',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='decoratie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diameter',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='diameter in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'fragment',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='fragment: rand, wand, bodem, oor etc',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'glazuur',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Glazuur',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'grootste_diameter',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Grootste diameter in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'hoogte',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Hoogte van voorwerp',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kleur',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='kleur',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'materiaalsoort',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oor',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='vorm en versiering van oor',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'past_aan',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='past aan andere nummers:',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'productiewijze',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Productie wijze',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rand',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='vorm en versiering van rand',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rand_bodem',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='diameter bodem in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rand_diameter',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='diameter rand in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='alleen invullen als voorwerp niet rond is',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'aantal_puzzelen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Aantal voor puzzelen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'associatie',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Associatie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bewerkingssporen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='bewerkingssporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'brandsporen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Brandsporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diersoort',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Diersoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'geconserveerd',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='geconserveerd',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'graf',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Soort graf',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'individunr',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Individunummer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'knaagsporen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Knaagsporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'leeftijd',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Leeftijd individu',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'lengte',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Lengte in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maat1',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Maat 1 in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maat2',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Maat 2 in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maat3',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Maat 3 in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maat4',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Maat 4 in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oriëntatie',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Oriëntatie (Links - Rechts)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'pathologie',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Pathologie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletdeel',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Skeletdeel',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Slijtage onderkaaks P4, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage_onderkaaks_DP4',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Slijtage onderkaaks DP4, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage_onderkaaks_M1',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Slijtage onderkaaks M1, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage_onderkaaks_M2',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Slijtage onderkaaks M2, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage_onderkaaks_M3',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Slijtage onderkaaks M3, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'symmetrie',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Symmetrie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vergroeiing',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Vergroeiing',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diameter_bodem',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Diameter van bodem',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diameter_rand',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='diameter rand in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'glassoort',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Soort glas',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'grootste',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='grootste diameter in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'past_aan_andere_nummers',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='past aan andere nummers:',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage_rand',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Randpercentage',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm_bodem_voet',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='vorm van de bodem/voet + eventuele merkjes',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm_versiering_cuppa',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='vorm en versiering van cuppa',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm_versiering_oor_stam',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='vorm en versiering van oor/stam',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'C14_datering',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='C14 datering mogelijk ja of nee',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'dendrodatering',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='dendrodatering mogelijk ja of nee',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'determinatieniveau',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='het determinatieniveau; bv. cf. = onzekere determinatie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gebruikssporen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='gebruikssporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'houtsoort',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='code voor de houtsoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'houtsoortcd',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='code voor de houtsoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'jaarring_bast_spint',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='jaarring, spint, bast',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'puntlengte',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='puntlengte : de lengte  in cm van de punt gemeten van hoogste kapvlak',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'puntvorm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='puntvorm : het aantal vlakken warrmee de punt is gemaakt halverwege de punt',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'stamcode',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='stamcode : 0 =onbekend',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'magering',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='magering',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maker',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Maker (vnl. i.g.v. kleipijpen)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oor_steel',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Oor steel',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oppervlakte',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='oppervlakte behandeling',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randdiameter',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Randdiameter in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randindex',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Randindex (RANDPER / 100)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randpercentage',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Randpercentage',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'subbaksel',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Subbaksel',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'type_rand',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='type rand',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'wanddikte',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='wanddikte',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'beschrijving_zool',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Verder beschrijving van de zool',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bewerking',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='bewerking',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bewerkinssporen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Bewerkinssporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bovenleer',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='bovenleer: bv. wreef, hiel, tong, etc.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kwaliteit',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='numismatische kwaliteitsaanduiding : goed, f.d.c.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'leersoort',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Leersoort (Naam dier)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'sluiting',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='sluiting: bv. veter, gesp, riem, etc.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'soort_sluiting',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Soort sluiting',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'toestand',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='toestand: nat of droog',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'type_bovenleer',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Type bovenleer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'verbinding',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='verbinding tussen zool en bovenleer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'zool',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='zool: dubbel, enkel, etc.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'zoolvorm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='zoolvorm: code volgens Goubitz, Stepping through time (bladzijde 82)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'breedte_kist_hoofdeinde',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'breedte_kist_voeteinde',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'lengte_kist',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'plaats',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='plaats van bewaring',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diverse',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='diverse: aangetast, licht aangetast, zwaar aangetast en/of geirriseerd',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'metaalsoort',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Metaal soort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oppervlak',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='oppervlak',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'aard_verwerving',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='koop, schenking, legaat, bruikleen etc.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'autoriteit',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='naam van vorst (met jaartallen), instantie, opdrachtgever',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'conditie',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='alleen invullen in uitzonderlijke situatie, restauratie nodig ?',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'eenheid',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='bv : kwart, halve, dubbele, 1, 10, 25',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gelegenheid',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='korte aanduiding',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'inventaris',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='huidig inventarisnummer (eventueel oude inv. nrs)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'jaartal',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='jaartal op voorwerp (of periode)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'keerzijde_tekst',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='volledige teks',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'land',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='land van uitgifte (politieke eenheid)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'muntplaats',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='plaats van aanmunting',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'muntsoort',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='in enkelvoud, bv daalder, gulden, cent',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'ontwerper',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='naam (met jaartallen)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'produktiewijze',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='alleen invullen indien nodig',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randafwerking',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='alleen invullen indien niet glad',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randschrift',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='volldedige tekst',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rubriek',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='grove indeling in gebied, periode of politieke eenheid',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'signalement',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='korte beschrijving, signalement',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'verworven_van',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='verworven van wie en wanneer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vindplaats',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='allleen voor(bodem)vondsten, waar en wanneer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'voorwaarden_verwerving',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='eventueel aan de verwerving verbonden voorwaarden',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'voorzijde_tekst',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='volledige teks',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'dikte',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='dikte in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'steengroep',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='Steengroep',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'steensoort',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='steensoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'subsoort',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_comment='subsoort',
               existing_nullable=True)
    op.alter_column('Def_Doos', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Foto', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageUUID',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageMiddleUUID',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageThumbUUID',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Plaatsing', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Project', 'projectnaam',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Project', 'toponiem',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Project', 'trefwoorden',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Project', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Put', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'vlaknr',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'aard',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'datering',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'vorm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'diepte',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'breedte_bovenkant',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'lengte_bovenkant',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'hoogte_bovenkant',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'hoogte_onderkant',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'breedte_onderkant',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'onderkant_NAP',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'profiel',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'richting',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'metselverband',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'steenformaat',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'jonger_dan',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'ouder_dan',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'sporen_zelfde_periode',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Standplaats', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Stelling', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vindplaats', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vindplaats', 'vindplaats',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vlak', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vondst', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'vlaknr',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'inhoud',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'datering',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'segment',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'vaknummer',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'verzamelwijze',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'vullingnr',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('observation', '_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=320),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observation', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'vullingnr',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'verzamelwijze',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'vaknummer',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'segment',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'datering',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'inhoud',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'vlaknr',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vlak', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vindplaats', 'vindplaats',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vindplaats', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Stelling', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Standplaats', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'sporen_zelfde_periode',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'ouder_dan',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'jonger_dan',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'steenformaat',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'metselverband',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'richting',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'profiel',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'onderkant_NAP',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'breedte_onderkant',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'hoogte_onderkant',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'hoogte_bovenkant',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'lengte_bovenkant',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'breedte_bovenkant',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'diepte',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'vorm',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'datering',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'aard',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'vlaknr',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Put', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Project', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Project', 'trefwoorden',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Project', 'toponiem',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Project', 'projectnaam',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Plaatsing', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageThumbUUID',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageMiddleUUID',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageUUID',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Foto', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Doos', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'subsoort',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='subsoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'steensoort',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='steensoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'steengroep',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Steengroep',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'dikte',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='dikte in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'voorzijde_tekst',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='volledige teks',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'voorwaarden_verwerving',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='eventueel aan de verwerving verbonden voorwaarden',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vindplaats',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='allleen voor(bodem)vondsten, waar en wanneer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'verworven_van',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='verworven van wie en wanneer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'signalement',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='korte beschrijving, signalement',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rubriek',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='grove indeling in gebied, periode of politieke eenheid',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randschrift',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='volldedige tekst',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randafwerking',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='alleen invullen indien niet glad',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'produktiewijze',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='alleen invullen indien nodig',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'ontwerper',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='naam (met jaartallen)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'muntsoort',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='in enkelvoud, bv daalder, gulden, cent',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'muntplaats',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='plaats van aanmunting',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'land',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='land van uitgifte (politieke eenheid)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'keerzijde_tekst',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='volledige teks',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'jaartal',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='jaartal op voorwerp (of periode)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'inventaris',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='huidig inventarisnummer (eventueel oude inv. nrs)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gelegenheid',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='korte aanduiding',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'eenheid',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='bv : kwart, halve, dubbele, 1, 10, 25',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'conditie',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='alleen invullen in uitzonderlijke situatie, restauratie nodig ?',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'autoriteit',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='naam van vorst (met jaartallen), instantie, opdrachtgever',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'aard_verwerving',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='koop, schenking, legaat, bruikleen etc.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oppervlak',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='oppervlak',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'metaalsoort',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Metaal soort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diverse',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='diverse: aangetast, licht aangetast, zwaar aangetast en/of geirriseerd',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'plaats',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='plaats van bewaring',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'lengte_kist',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'breedte_kist_voeteinde',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'breedte_kist_hoofdeinde',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'zoolvorm',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='zoolvorm: code volgens Goubitz, Stepping through time (bladzijde 82)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'zool',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='zool: dubbel, enkel, etc.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'verbinding',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='verbinding tussen zool en bovenleer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'type_bovenleer',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Type bovenleer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'toestand',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='toestand: nat of droog',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'soort_sluiting',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Soort sluiting',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'sluiting',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='sluiting: bv. veter, gesp, riem, etc.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'leersoort',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Leersoort (Naam dier)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kwaliteit',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='numismatische kwaliteitsaanduiding : goed, f.d.c.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bovenleer',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='bovenleer: bv. wreef, hiel, tong, etc.',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bewerkinssporen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Bewerkinssporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bewerking',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='bewerking',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'beschrijving_zool',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Verder beschrijving van de zool',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'wanddikte',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='wanddikte',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'type_rand',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='type rand',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'subbaksel',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Subbaksel',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randpercentage',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Randpercentage',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randindex',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Randindex (RANDPER / 100)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'randdiameter',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Randdiameter in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oppervlakte',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='oppervlakte behandeling',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oor_steel',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Oor steel',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maker',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Maker (vnl. i.g.v. kleipijpen)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'magering',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='magering',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'stamcode',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='stamcode : 0 =onbekend',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'puntvorm',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='puntvorm : het aantal vlakken warrmee de punt is gemaakt halverwege de punt',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'puntlengte',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='puntlengte : de lengte  in cm van de punt gemeten van hoogste kapvlak',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'jaarring_bast_spint',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='jaarring, spint, bast',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'houtsoortcd',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='code voor de houtsoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'houtsoort',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='code voor de houtsoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gebruikssporen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='gebruikssporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'determinatieniveau',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='het determinatieniveau; bv. cf. = onzekere determinatie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'dendrodatering',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='dendrodatering mogelijk ja of nee',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'C14_datering',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='C14 datering mogelijk ja of nee',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm_versiering_oor_stam',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='vorm en versiering van oor/stam',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm_versiering_cuppa',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='vorm en versiering van cuppa',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm_bodem_voet',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='vorm van de bodem/voet + eventuele merkjes',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage_rand',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Randpercentage',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'past_aan_andere_nummers',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='past aan andere nummers:',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'grootste',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='grootste diameter in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'glassoort',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Soort glas',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diameter_rand',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='diameter rand in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diameter_bodem',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Diameter van bodem',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vergroeiing',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Vergroeiing',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'symmetrie',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Symmetrie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage_onderkaaks_M3',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Slijtage onderkaaks M3, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage_onderkaaks_M2',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Slijtage onderkaaks M2, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage_onderkaaks_M1',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Slijtage onderkaaks M1, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage_onderkaaks_DP4',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Slijtage onderkaaks DP4, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'slijtage',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Slijtage onderkaaks P4, Grant 1982',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletdeel',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Skeletdeel',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'pathologie',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Pathologie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oriëntatie',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Oriëntatie (Links - Rechts)',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maat4',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Maat 4 in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maat3',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Maat 3 in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maat2',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Maat 2 in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'maat1',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Maat 1 in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'lengte',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Lengte in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'leeftijd',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Leeftijd individu',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'knaagsporen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Knaagsporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'individunr',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Individunummer',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'graf',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Soort graf',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'geconserveerd',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='geconserveerd',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diersoort',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Diersoort',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'brandsporen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Brandsporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bewerkingssporen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='bewerkingssporen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'associatie',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Associatie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'aantal_puzzelen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Aantal voor puzzelen',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vorm',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='alleen invullen als voorwerp niet rond is',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rand_diameter',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='diameter rand in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rand_bodem',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='diameter bodem in millimeters, 0 = niet gemeten',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rand',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='vorm en versiering van rand',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'productiewijze',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Productie wijze',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'past_aan',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='past aan andere nummers:',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'oor',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='vorm en versiering van oor',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'materiaalsoort',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kleur',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='kleur',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'hoogte',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Hoogte van voorwerp',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'grootste_diameter',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Grootste diameter in cm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'glazuur',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Glazuur',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'fragment',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='fragment: rand, wand, bodem, oor etc',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'diameter',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='diameter in mm',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'decoratie',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='decoratie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'codes',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='codes van type',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'categorie',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='categorie',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bodem',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Bodem',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'bakseltype',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='bakseltype',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'baksel',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='Baksel',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'vondstomstandigheden',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'versiering',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'typenaam',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'publicatiecode',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'plek',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'naam_voorwerp',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'materiaal',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='bv : goud, zilver',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'formaat_vericaal',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'formaat_horizontaal',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'mai',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_comment='MAI, minimum aantal individuen, 0 = onbekend, meer dan 1',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'groep',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gewicht',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'compleetheid',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'catalogus',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'afmetingen',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'ABRcodering',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'literatuur',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'datering',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'origine',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'functievoorwerp',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'typecd',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'typevoorwerp',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', '_id',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
