"""empty message

Revision ID: 599aca5729d8
Revises: 
Create Date: 2020-02-14 19:57:46.494981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599aca5729d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('testveld', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Artefact', 'testveld')
    # ### end Alembic commands ###
