"""empty message

Revision ID: 601ab3bb74f3
Revises: db02a2699d17
Create Date: 2020-02-15 06:30:12.986662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601ab3bb74f3'
down_revision = 'db02a2699d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('DoosID', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_Def_Artefact_DoosID'), 'Def_Artefact', ['DoosID'], unique=False)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Doos', ['DoosID'], ['primary_key'])
    op.drop_index('ix_Def_Doos_ArtefactID', table_name='Def_Doos')
    op.drop_constraint('Def_Doos_ArtefactID_fkey', 'Def_Doos', type_='foreignkey')
    op.drop_column('Def_Doos', 'ArtefactID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Doos', sa.Column('ArtefactID', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('Def_Doos_ArtefactID_fkey', 'Def_Doos', 'Def_Artefact', ['ArtefactID'], ['primary_key'])
    op.create_index('ix_Def_Doos_ArtefactID', 'Def_Doos', ['ArtefactID'], unique=False)
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Artefact_DoosID'), table_name='Def_Artefact')
    op.drop_column('Def_Artefact', 'DoosID')
    # ### end Alembic commands ###
