"""empty message

Revision ID: 60929607aacf
Revises: 2a5f715a7eac
Create Date: 2023-03-22 20:29:51.888637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60929607aacf'
down_revision = '2a5f715a7eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_Artefact', schema=None) as batch_op:
        batch_op.alter_column('max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)

    with op.batch_alter_table('Def_Monster_Botanie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dt_soort_plantID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dt_soort_deelID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dt_soort_staatID', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Def_Monster_Botanie_dt_soort_deelID'), ['dt_soort_deelID'], unique=False)
        batch_op.create_index(batch_op.f('ix_Def_Monster_Botanie_dt_soort_plantID'), ['dt_soort_plantID'], unique=False)
        batch_op.create_index(batch_op.f('ix_Def_Monster_Botanie_dt_soort_staatID'), ['dt_soort_staatID'], unique=False)
        batch_op.create_foreign_key(None, 'Def_DT_Soort_Plant', ['dt_soort_plantID'], ['primary_key'], deferrable=True)
        batch_op.create_foreign_key(None, 'Def_DT_Soort_Staat', ['dt_soort_staatID'], ['primary_key'], deferrable=True)
        batch_op.create_foreign_key(None, 'Def_DT_Soort_Deel', ['dt_soort_deelID'], ['primary_key'], deferrable=True)

    with op.batch_alter_table('Def_Monster_Schelp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dt_soort_schelpID', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Def_Monster_Schelp_dt_soort_schelpID'), ['dt_soort_schelpID'], unique=False)
        batch_op.create_foreign_key(None, 'Def_DT_Soort_Schelp', ['dt_soort_schelpID'], ['primary_key'], deferrable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_Monster_Schelp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Def_Monster_Schelp_dt_soort_schelpID'))
        batch_op.drop_column('dt_soort_schelpID')

    with op.batch_alter_table('Def_Monster_Botanie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Def_Monster_Botanie_dt_soort_staatID'))
        batch_op.drop_index(batch_op.f('ix_Def_Monster_Botanie_dt_soort_plantID'))
        batch_op.drop_index(batch_op.f('ix_Def_Monster_Botanie_dt_soort_deelID'))
        batch_op.drop_column('dt_soort_staatID')
        batch_op.drop_column('dt_soort_deelID')
        batch_op.drop_column('dt_soort_plantID')

    with op.batch_alter_table('Def_Artefact', schema=None) as batch_op:
        batch_op.alter_column('wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)

    # ### end Alembic commands ###
