"""empty message

Revision ID: 6104c739a453
Revises: a0c146800318
Create Date: 2020-02-26 14:27:02.919803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6104c739a453'
down_revision = 'a0c146800318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Artefact', 'vondstnr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('vondstnr', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
