"""Spoor verbeterd 2

Revision ID: 616d42eb7a7a
Revises: dcaccb245057
Create Date: 2022-02-16 14:32:40.641507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616d42eb7a7a'
down_revision = 'dcaccb245057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('gecoupeerd', sa.Text(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('onderkant_NAP', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Spoor', 'onderkant_NAP')
    op.drop_column('Def_Spoor', 'gecoupeerd')
    # ### end Alembic commands ###
