"""Monstervelden toegevoegd

Revision ID: 61ad57846915
Revises: 0dd770fcc20f
Create Date: 2022-08-19 13:55:38.839103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ad57846915'
down_revision = '0dd770fcc20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Monster', sa.Column('grondsoort', sa.String(length=250), nullable=True))
    op.add_column('Def_Monster', sa.Column('restvolume', sa.Float(), nullable=True))
    op.add_column('Def_Monster', sa.Column('datum_zeven', sa.String(length=80), nullable=True))
    op.add_column('Def_Monster', sa.Column('r_analysewaardig_zo', sa.String(length=20), nullable=True))
    op.add_column('Def_Monster', sa.Column('r_analysewaardig_bo', sa.String(length=20), nullable=True))
    op.add_column('Def_Monster', sa.Column('r_concentratie_zo', sa.String(length=20), nullable=True))
    op.add_column('Def_Monster', sa.Column('r_concentratie_bo', sa.String(length=20), nullable=True))
    op.add_column('Def_Monster', sa.Column('r_conservering_zo', sa.String(length=20), nullable=True))
    op.add_column('Def_Monster', sa.Column('r_conservering_bo', sa.String(length=20), nullable=True))
    op.add_column('Def_Monster', sa.Column('r_diversiteit_zo', sa.String(length=20), nullable=True))
    op.add_column('Def_Monster', sa.Column('r_diversiteit_bo', sa.String(length=20), nullable=True))
    op.add_column('Def_Monster_Botanie', sa.Column('determinatie', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Monster_Botanie', 'determinatie')
    op.drop_column('Def_Monster', 'r_diversiteit_bo')
    op.drop_column('Def_Monster', 'r_diversiteit_zo')
    op.drop_column('Def_Monster', 'r_conservering_bo')
    op.drop_column('Def_Monster', 'r_conservering_zo')
    op.drop_column('Def_Monster', 'r_concentratie_bo')
    op.drop_column('Def_Monster', 'r_concentratie_zo')
    op.drop_column('Def_Monster', 'r_analysewaardig_bo')
    op.drop_column('Def_Monster', 'r_analysewaardig_zo')
    op.drop_column('Def_Monster', 'datum_zeven')
    op.drop_column('Def_Monster', 'restvolume')
    op.drop_column('Def_Monster', 'grondsoort')
    # ### end Alembic commands ###
