"""empty message

Revision ID: 6378feb44a8c
Revises: 01ea44788ba7
Create Date: 2020-02-26 17:04:50.847423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6378feb44a8c'
down_revision = '01ea44788ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Doos', sa.Column('vaknr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Doos', 'vaknr')
    # ### end Alembic commands ###
