"""Dateringvelden aangepast

Revision ID: 649ffb034135
Revises: 0ce6fa103a35
Create Date: 2022-06-11 14:57:02.031480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649ffb034135'
down_revision = '0ce6fa103a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('artefactdatering_vanaf', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('artefactdatering_tot', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('datering_vanaf', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('datering_tot', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('vondstdatering_vanaf', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('vondstdatering_tot', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('spoordatering_vanaf', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('spoordatering_tot', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Artefact_datering_tot'), 'Def_Artefact', ['datering_tot'], unique=False)
    op.create_index(op.f('ix_Def_Artefact_datering_vanaf'), 'Def_Artefact', ['datering_vanaf'], unique=False)
    op.create_index(op.f('ix_Def_Artefact_spoordatering_tot'), 'Def_Artefact', ['spoordatering_tot'], unique=False)
    op.create_index(op.f('ix_Def_Artefact_spoordatering_vanaf'), 'Def_Artefact', ['spoordatering_vanaf'], unique=False)
    op.create_index(op.f('ix_Def_Artefact_vondstdatering_tot'), 'Def_Artefact', ['vondstdatering_tot'], unique=False)
    op.create_index(op.f('ix_Def_Artefact_vondstdatering_vanaf'), 'Def_Artefact', ['vondstdatering_vanaf'], unique=False)
    op.drop_column('Def_Artefact', 'dateringvanaf')
    op.drop_column('Def_Artefact', 'dateringtot')
    op.drop_column('Def_Artefact', 'datering')
    op.add_column('Def_Spoor', sa.Column('spoordatering_vanaf', sa.Integer(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('spoordatering_tot', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Spoor_spoordatering_tot'), 'Def_Spoor', ['spoordatering_tot'], unique=False)
    op.create_index(op.f('ix_Def_Spoor_spoordatering_vanaf'), 'Def_Spoor', ['spoordatering_vanaf'], unique=False)
    op.drop_column('Def_Spoor', 'dateringvanaf')
    op.drop_column('Def_Spoor', 'dateringtot')
    op.drop_column('Def_Spoor', 'datering')
    op.add_column('Def_Vondst', sa.Column('vondstdatering_vanaf', sa.Integer(), nullable=True))
    op.add_column('Def_Vondst', sa.Column('vondstdatering_tot', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Vondst_vondstdatering_tot'), 'Def_Vondst', ['vondstdatering_tot'], unique=False)
    op.create_index(op.f('ix_Def_Vondst_vondstdatering_vanaf'), 'Def_Vondst', ['vondstdatering_vanaf'], unique=False)
    op.drop_column('Def_Vondst', 'dateringvanaf')
    op.drop_column('Def_Vondst', 'dateringtot')
    op.drop_column('Def_Vondst', 'datering')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vondst', sa.Column('datering', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('Def_Vondst', sa.Column('dateringtot', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Def_Vondst', sa.Column('dateringvanaf', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Def_Vondst_vondstdatering_vanaf'), table_name='Def_Vondst')
    op.drop_index(op.f('ix_Def_Vondst_vondstdatering_tot'), table_name='Def_Vondst')
    op.drop_column('Def_Vondst', 'vondstdatering_tot')
    op.drop_column('Def_Vondst', 'vondstdatering_vanaf')
    op.add_column('Def_Spoor', sa.Column('datering', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('Def_Spoor', sa.Column('dateringtot', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Def_Spoor', sa.Column('dateringvanaf', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Def_Spoor_spoordatering_vanaf'), table_name='Def_Spoor')
    op.drop_index(op.f('ix_Def_Spoor_spoordatering_tot'), table_name='Def_Spoor')
    op.drop_column('Def_Spoor', 'spoordatering_tot')
    op.drop_column('Def_Spoor', 'spoordatering_vanaf')
    op.add_column('Def_Artefact', sa.Column('datering', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('Def_Artefact', sa.Column('dateringtot', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Def_Artefact', sa.Column('dateringvanaf', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Def_Artefact_vondstdatering_vanaf'), table_name='Def_Artefact')
    op.drop_index(op.f('ix_Def_Artefact_vondstdatering_tot'), table_name='Def_Artefact')
    op.drop_index(op.f('ix_Def_Artefact_spoordatering_vanaf'), table_name='Def_Artefact')
    op.drop_index(op.f('ix_Def_Artefact_spoordatering_tot'), table_name='Def_Artefact')
    op.drop_index(op.f('ix_Def_Artefact_datering_vanaf'), table_name='Def_Artefact')
    op.drop_index(op.f('ix_Def_Artefact_datering_tot'), table_name='Def_Artefact')
    op.drop_column('Def_Artefact', 'spoordatering_tot')
    op.drop_column('Def_Artefact', 'spoordatering_vanaf')
    op.drop_column('Def_Artefact', 'vondstdatering_tot')
    op.drop_column('Def_Artefact', 'vondstdatering_vanaf')
    op.drop_column('Def_Artefact', 'datering_tot')
    op.drop_column('Def_Artefact', 'datering_vanaf')
    op.drop_column('Def_Artefact', 'artefactdatering_tot')
    op.drop_column('Def_Artefact', 'artefactdatering_vanaf')
    # ### end Alembic commands ###
