"""empty message

Revision ID: 64f6635ac89e
Revises: 6378feb44a8c
Create Date: 2020-02-26 17:14:56.188357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f6635ac89e'
down_revision = '6378feb44a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Fotos', sa.Column('fotosubnr', sa.Text(), nullable=True))
    op.add_column('Def_Fotos', sa.Column('projectID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Fotos_projectID'), 'Def_Fotos', ['projectID'], unique=False)
    op.create_foreign_key(None, 'Def_Fotos', 'Def_Project', ['projectID'], ['primary_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Fotos', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Fotos_projectID'), table_name='Def_Fotos')
    op.drop_column('Def_Fotos', 'projectID')
    op.drop_column('Def_Fotos', 'fotosubnr')
    # ### end Alembic commands ###
