"""Key- en table-velden verwijderd

Revision ID: 65945461f8da
Revises: c1d619060bc6
Create Date: 2022-02-04 13:41:36.736952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65945461f8da'
down_revision = 'c1d619060bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Artefact', 'table')
    op.drop_column('Def_Doos', 'table')
    op.drop_column('Def_Doos', 'key')
    op.drop_column('Def_Foto', 'key_vondst')
    op.drop_column('Def_Foto', 'key_project_type')
    op.drop_column('Def_Foto', 'key_artefact')
    op.drop_column('Def_Foto', 'key_project')
    op.drop_column('Def_Foto', 'key')
    op.drop_column('Def_Plaatsing', 'key_doos')
    op.drop_column('Def_Plaatsing', 'key_magazijnlocatie')
    op.drop_column('Def_Project', 'table')
    op.drop_column('Def_Project', 'key')
    op.drop_column('Def_Spoor', 'key_put')
    op.drop_column('Def_Spoor', 'key_spoor')
    op.drop_column('Def_Spoor', 'key_vlak')
    op.drop_column('Def_Spoor', 'key')
    op.drop_column('Def_Standplaats', 'table')
    op.drop_column('Def_Standplaats', 'key')
    op.drop_column('Def_Stelling', 'table')
    op.drop_column('Def_Stelling', 'key')
    op.drop_column('Def_Vlak', 'key')
    op.drop_column('Def_Vlak', 'key_put')
    op.drop_column('Def_Vondst', 'key_put')
    op.drop_column('Def_Vondst', 'key_vlak')
    op.drop_column('Def_Vondst', 'key_project')
    op.drop_column('Def_Vondst', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vondst', sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Vondst', sa.Column('key_project', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Vondst', sa.Column('key_vlak', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Vondst', sa.Column('key_put', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Vlak', sa.Column('key_put', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Vlak', sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Stelling', sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Stelling', sa.Column('table', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Standplaats', sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Standplaats', sa.Column('table', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Spoor', sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Spoor', sa.Column('key_vlak', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Spoor', sa.Column('key_spoor', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Spoor', sa.Column('key_put', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Project', sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Project', sa.Column('table', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Plaatsing', sa.Column('key_magazijnlocatie', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Def_Plaatsing', sa.Column('key_doos', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Def_Foto', sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Foto', sa.Column('key_project', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Foto', sa.Column('key_artefact', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Foto', sa.Column('key_project_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Foto', sa.Column('key_vondst', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Doos', sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Doos', sa.Column('table', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('Def_Artefact', sa.Column('table', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
