"""Spoor verbeterd 3

Revision ID: 67478736bf39
Revises: 616d42eb7a7a
Create Date: 2022-02-16 14:39:36.108234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67478736bf39'
down_revision = '616d42eb7a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Def_Put_projectID_fkey', 'Def_Put', type_='foreignkey')
    op.create_foreign_key(None, 'Def_Put', 'Def_Project', ['projectID'], ['primary_key'], deferrable=True)
    op.add_column('Def_Spoor', sa.Column('coupnrs', sa.Text(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('afgewerkt', sa.Text(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('breedte_onderkant', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Spoor', 'breedte_onderkant')
    op.drop_column('Def_Spoor', 'afgewerkt')
    op.drop_column('Def_Spoor', 'coupnrs')
    op.drop_constraint(None, 'Def_Put', type_='foreignkey')
    op.create_foreign_key('Def_Put_projectID_fkey', 'Def_Put', 'Def_Project', ['projectID'], ['primary_key'])
    # ### end Alembic commands ###
