"""empty message

Revision ID: 693d2e48f20b
Revises: d315f9fc15c2
Create Date: 2020-02-28 21:11:56.779184

"""
from alembic import op
import sqlalchemy as sa
from fab_addon_geoalchemy.models import GeoSQLAInterface, Geometry


# revision identifiers, used by Alembic.
revision = '693d2e48f20b'
down_revision = 'd315f9fc15c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    #op.drop_index('idx_Def_Artefact_location', table_name='Def_Artefact')
    op.add_column('Def_Project', sa.Column('location', Geometry(geometry_type='POINT', srid=28992), nullable=True))
    op.create_index('idx_Def_project_location', 'Def_Project', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Project', 'location')
    op.create_index('idx_Def_Project_location', 'Def_Project', ['location'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
