"""Attributen verwijderd

Revision ID: 6a50d8ff3c77
Revises: ee68b4b6e95f
Create Date: 2022-05-04 15:57:15.006802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a50d8ff3c77'
down_revision = 'ee68b4b6e95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('abr_materiaal', sa.String(length=1024), nullable=True))
    op.drop_column('Def_Artefact', 'ABRcodering')
    op.drop_column('Def_Vondst', 'verzamelwijze')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vondst', sa.Column('verzamelwijze', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('Def_Artefact', sa.Column('ABRcodering', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('Def_Artefact', 'abr_materiaal')
    # ### end Alembic commands ###
