"""Conservering toegevoegd

Revision ID: 6db27327b501
Revises: 0503e0cc7c65
Create Date: 2023-02-23 20:38:43.836683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db27327b501'
down_revision = '0503e0cc7c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('Def_Bestand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fotomoment', sa.Enum('Voor', 'Tijdens', 'Na', name='conserverinsgfotomomentenum'), nullable=True))
        batch_op.add_column(sa.Column('conserveringID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Def_Conservering', ['conserveringID'], ['primary_key'])

    with op.batch_alter_table('Def_Conservering', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uitvoerderID', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_Def_Conservering_partijID')
        batch_op.create_index(batch_op.f('ix_Def_Conservering_uitvoerderID'), ['uitvoerderID'], unique=False)
        batch_op.drop_constraint('Def_Conservering_partijID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Def_Partij', ['uitvoerderID'], ['primary_key'], deferrable=True)
        batch_op.drop_column('partijID')

    with op.batch_alter_table('Def_Project', schema=None) as batch_op:
        batch_op.alter_column('ft_search',
               existing_type=sa.VARCHAR(),
               comment='technisch veld om fulltext zoeken te ondersteunen',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_Project', schema=None) as batch_op:
        batch_op.alter_column('ft_search',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='technisch veld om fulltext zoeken te ondersteunen',
               existing_nullable=True)

    with op.batch_alter_table('Def_Conservering', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partijID', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Def_Conservering_partijID_fkey', 'Def_Partij', ['partijID'], ['primary_key'], deferrable=True)
        batch_op.drop_index(batch_op.f('ix_Def_Conservering_uitvoerderID'))
        batch_op.create_index('ix_Def_Conservering_partijID', ['partijID'], unique=False)
        batch_op.drop_column('uitvoerderID')

    with op.batch_alter_table('Def_Bestand', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conserveringID')
        batch_op.drop_column('fotomoment')


    # ### end Alembic commands ###
