"""empty message

Revision ID: 6e187e33454b
Revises: 939c3cd078cb
Create Date: 2020-03-08 21:05:36.795461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e187e33454b'
down_revision = '939c3cd078cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Def_Spoor_projectID'), 'Def_Spoor', ['projectID'], unique=False)
    op.create_foreign_key(None, 'Def_Spoor', 'Def_Project', ['projectID'], ['primary_key'])
    op.add_column('Def_Vondst', sa.Column('datering', sa.String(length=200), nullable=True))
    op.add_column('Def_Vondst', sa.Column('dateringtot', sa.Integer(), nullable=True))
    op.add_column('Def_Vondst', sa.Column('dateringvanaf', sa.Integer(), nullable=True))
    op.add_column('Def_Vondst', sa.Column('putID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Vondst_putID'), 'Def_Vondst', ['putID'], unique=False)
    op.create_foreign_key(None, 'Def_Vondst', 'Def_Put', ['putID'], ['primary_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Vondst', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Vondst_putID'), table_name='Def_Vondst')
    op.drop_column('Def_Vondst', 'putID')
    op.drop_column('Def_Vondst', 'dateringvanaf')
    op.drop_column('Def_Vondst', 'dateringtot')
    op.drop_column('Def_Vondst', 'datering')
    op.drop_constraint(None, 'Def_Spoor', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Spoor_projectID'), table_name='Def_Spoor')
    # ### end Alembic commands ###
