"""Artefact uitgebreid

Revision ID: 72d166bcd164
Revises: 8b06f63cb8b5
Create Date: 2022-02-25 16:22:41.575358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d166bcd164'
down_revision = '8b06f63cb8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('ABRcodering', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('aantal', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('afmetingen', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('bibliografie', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('catalogus', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('compleetheid', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('conservering', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('diversen', sa.Text(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('gewicht', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('groep', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('mai', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('maten', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('materiaal', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('naam_voorwerp', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('plek', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('publicatiecode', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('soortvoorwerp', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('typenaam', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('versiering', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('vondstomstandigheden', sa.String(length=200), nullable=True))
    op.add_column('Def_Artefact', sa.Column('weggegooid', sa.Integer(), nullable=True))
    op.drop_constraint('Def_Artefact_doosID_fkey', 'Def_Artefact', type_='foreignkey')
    op.drop_constraint('Def_Artefact_projectID_fkey', 'Def_Artefact', type_='foreignkey')
    op.drop_constraint('Def_Artefact_putID_fkey', 'Def_Artefact', type_='foreignkey')
    op.drop_constraint('Def_Artefact_vondstID_fkey', 'Def_Artefact', type_='foreignkey')
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Project', ['projectID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Put', ['putID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Doos', ['doosID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Vondst', ['vondstID'], ['primary_key'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.create_foreign_key('Def_Artefact_vondstID_fkey', 'Def_Artefact', 'Def_Vondst', ['vondstID'], ['primary_key'])
    op.create_foreign_key('Def_Artefact_putID_fkey', 'Def_Artefact', 'Def_Put', ['putID'], ['primary_key'])
    op.create_foreign_key('Def_Artefact_projectID_fkey', 'Def_Artefact', 'Def_Project', ['projectID'], ['primary_key'])
    op.create_foreign_key('Def_Artefact_doosID_fkey', 'Def_Artefact', 'Def_Doos', ['doosID'], ['primary_key'])
    op.drop_column('Def_Artefact', 'weggegooid')
    op.drop_column('Def_Artefact', 'vondstomstandigheden')
    op.drop_column('Def_Artefact', 'versiering')
    op.drop_column('Def_Artefact', 'typenaam')
    op.drop_column('Def_Artefact', 'soortvoorwerp')
    op.drop_column('Def_Artefact', 'publicatiecode')
    op.drop_column('Def_Artefact', 'plek')
    op.drop_column('Def_Artefact', 'naam_voorwerp')
    op.drop_column('Def_Artefact', 'materiaal')
    op.drop_column('Def_Artefact', 'maten')
    op.drop_column('Def_Artefact', 'mai')
    op.drop_column('Def_Artefact', 'groep')
    op.drop_column('Def_Artefact', 'gewicht')
    op.drop_column('Def_Artefact', 'diversen')
    op.drop_column('Def_Artefact', 'conservering')
    op.drop_column('Def_Artefact', 'compleetheid')
    op.drop_column('Def_Artefact', 'catalogus')
    op.drop_column('Def_Artefact', 'bibliografie')
    op.drop_column('Def_Artefact', 'afmetingen')
    op.drop_column('Def_Artefact', 'aantal')
    op.drop_column('Def_Artefact', 'ABRcodering')
    # ### end Alembic commands ###
