"""Project verbeterd

Revision ID: 784af07b9e9c
Revises: 08188ed2e4a2
Create Date: 2022-02-16 15:08:45.422279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784af07b9e9c'
down_revision = '08188ed2e4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Project', sa.Column('key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Project', 'key')
    # ### end Alembic commands ###
