"""Nieuwe enum

Revision ID: 7a4b07100370
Revises: d8327a171f86
Create Date: 2023-01-23 14:48:42.154472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4b07100370'
down_revision = 'd8327a171f86'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_Bestand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bestandsoort', sa.Enum('Bouwtekeningen, Topografie en Geologie', 'Veldtekeningen', 'Overzichtstekeningen', 'Objecttekening op millimeter papier/film', 'Uitwerkingstekeningen', 'Veldtekening', 'Publiceerbaar', 'Objecttekening publiceerbaar', 'Overige tekening', 'Sfeerfoto', 'Opgravingsfoto', 'Objectfoto', 'Overige afbeelding', 'Rapportage', 'Archeologische Rapportage', 'Archeologische Notitie', 'Conserveringsrapport', 'Overige Rapportage', 'Bestand', name='discrbestandsoortenum'), nullable=True))
        batch_op.create_index(batch_op.f('ix_Def_Bestand_bestandsoort'), ['bestandsoort'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_Bestand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Def_Bestand_bestandsoort'))
        batch_op.drop_column('bestandsoort')

