"""ABR refs rename

Revision ID: 7ad8c8efb48f
Revises: 3ecf71189c13
Create Date: 2022-11-18 14:49:55.944088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad8c8efb48f'
down_revision = '3ecf71189c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('abr_materiaalID', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('abr_submateriaalID', sa.Integer(), nullable=True))
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.drop_index('ix_Def_Artefact_abr_materiaal_id', table_name='Def_Artefact')
    op.drop_index('ix_Def_Artefact_sub_abr_materiaal_id', table_name='Def_Artefact')
    op.create_index(op.f('ix_Def_Artefact_abr_materiaalID'), 'Def_Artefact', ['abr_materiaalID'], unique=False)
    op.create_index(op.f('ix_Def_Artefact_abr_submateriaalID'), 'Def_Artefact', ['abr_submateriaalID'], unique=False)
    op.drop_constraint('Def_Artefact_abr_materiaal_id_fkey', 'Def_Artefact', type_='foreignkey')
    op.drop_constraint('Def_Artefact_sub_abr_materiaal_id_fkey', 'Def_Artefact', type_='foreignkey')
    op.create_foreign_key(None, 'Def_Artefact', 'Def_ABR', ['abr_materiaalID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_ABR', ['abr_submateriaalID'], ['primary_key'], deferrable=True)
    op.drop_column('Def_Artefact', 'sub_abr_materiaal_id')
    op.drop_column('Def_Artefact', 'abr_materiaal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('abr_materiaal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Def_Artefact', sa.Column('sub_abr_materiaal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.create_foreign_key('Def_Artefact_sub_abr_materiaal_id_fkey', 'Def_Artefact', 'Def_ABR', ['sub_abr_materiaal_id'], ['primary_key'], deferrable=True)
    op.create_foreign_key('Def_Artefact_abr_materiaal_id_fkey', 'Def_Artefact', 'Def_ABR', ['abr_materiaal_id'], ['primary_key'], deferrable=True)
    op.drop_index(op.f('ix_Def_Artefact_abr_submateriaalID'), table_name='Def_Artefact')
    op.drop_index(op.f('ix_Def_Artefact_abr_materiaalID'), table_name='Def_Artefact')
    op.create_index('ix_Def_Artefact_sub_abr_materiaal_id', 'Def_Artefact', ['sub_abr_materiaal_id'], unique=False)
    op.create_index('ix_Def_Artefact_abr_materiaal_id', 'Def_Artefact', ['abr_materiaal_id'], unique=False)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.drop_column('Def_Artefact', 'abr_submateriaalID')
    op.drop_column('Def_Artefact', 'abr_materiaalID')
    # ### end Alembic commands ###
