"""empty message

Revision ID: 7ebf557eddc6
Revises: 954ca660b1cf
Create Date: 2020-02-15 17:36:35.745606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ebf557eddc6'
down_revision = '954ca660b1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('ArtefactsoortID', sa.Integer(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('DoosID', sa.BigInteger(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('ProjectID', sa.BigInteger(), nullable=True))
    op.add_column('Def_Artefact', sa.Column('testveld', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_Def_Artefact_ArtefactsoortID'), 'Def_Artefact', ['ArtefactsoortID'], unique=False)
    op.create_index(op.f('ix_Def_Artefact_DoosID'), 'Def_Artefact', ['DoosID'], unique=False)
    op.create_index(op.f('ix_Def_Artefact_ProjectID'), 'Def_Artefact', ['ProjectID'], unique=False)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Doos', ['DoosID'], ['primary_key'])
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Project', ['ProjectID'], ['primary_key'])
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Artefactsoort', ['ArtefactsoortID'], ['ArtefactsoortID'])
    op.add_column('Def_Doos', sa.Column('StellingID', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_Def_Doos_StellingID'), 'Def_Doos', ['StellingID'], unique=False)
    op.create_foreign_key(None, 'Def_Doos', 'Def_Stelling', ['StellingID'], ['primary_key'])
    op.add_column('Def_Fotos', sa.Column('photo', sa.String(length=40), nullable=True))
    op.drop_column('Def_Project', 'brondata')
    op.drop_column('Def_Project', '_id')
    op.drop_column('Def_Spoor', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('Def_Project', sa.Column('_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('Def_Project', sa.Column('brondata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('Def_Fotos', 'photo')
    op.drop_constraint(None, 'Def_Doos', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Doos_StellingID'), table_name='Def_Doos')
    op.drop_column('Def_Doos', 'StellingID')
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Artefact_ProjectID'), table_name='Def_Artefact')
    op.drop_index(op.f('ix_Def_Artefact_DoosID'), table_name='Def_Artefact')
    op.drop_index(op.f('ix_Def_Artefact_ArtefactsoortID'), table_name='Def_Artefact')
    op.drop_column('Def_Artefact', 'testveld')
    op.drop_column('Def_Artefact', 'ProjectID')
    op.drop_column('Def_Artefact', 'DoosID')
    op.drop_column('Def_Artefact', 'ArtefactsoortID')
    # ### end Alembic commands ###
