"""Rapportage uitgebreid

Revision ID: 81197bc8968d
Revises: d4fe003efd3e
Create Date: 2023-01-21 10:40:36.788333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81197bc8968d'
down_revision = 'd4fe003efd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_Artefact', schema=None) as batch_op:
        batch_op.alter_column('max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)

    with op.batch_alter_table('Def_Bestand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titel', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('type_onderzoek', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('periode_uitvoering', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('jaar_uitgave', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auteur', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('definitief', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rob', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('kb', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archief', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ciscode', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_Bestand', schema=None) as batch_op:
        batch_op.drop_column('ciscode')
        batch_op.drop_column('archief')
        batch_op.drop_column('kb')
        batch_op.drop_column('rob')
        batch_op.drop_column('definitief')
        batch_op.drop_column('auteur')
        batch_op.drop_column('jaar_uitgave')
        batch_op.drop_column('periode_uitvoering')
        batch_op.drop_column('type_onderzoek')
        batch_op.drop_column('titel')

    with op.batch_alter_table('Def_Artefact', schema=None) as batch_op:
        batch_op.alter_column('wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)

    # ### end Alembic commands ###
