"""Foto enumeratie

Revision ID: 81637d2c77b5
Revises: 649ffb034135
Create Date: 2022-07-06 12:05:33.005037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Enum
import shared.const as const
import enum



# revision identifiers, used by Alembic.
revision = '81637d2c77b5'
down_revision = '649ffb034135'
branch_labels = None
depends_on = None


class DiscrFotosoortEnum(enum.Enum): 
    Objectfoto = const.OBJECTFOTO
    Opgravingsfoto = const.OPGRAVINGSFOTO
    Velddocument = const.VELDDOCUMENT
    Overige_afbeelding = const.OVERIGE_AFBEELDING
    Afbeelding = const.AFBEELDING


def upgrade():
    op.add_column('Def_Foto', sa.Column('fotosoort', sa.Enum(const.OBJECTFOTO, const.OPGRAVINGSFOTO, const.VELDDOCUMENT, const.OVERIGE_AFBEELDING, const.AFBEELDING, name='discrfotosoortenum'), nullable=True))
    op.create_index(op.f('ix_Def_Foto_fotosoort'), 'Def_Foto', ['fotosoort'], unique=False)


    foto_table = table('Def_Foto',
        column('directory', String),
        column('fototype', String),
        column('fotosoort', String)
    )
    op.execute(
        foto_table.update().
            values({'fotosoort':op.inline_literal(const.OVERIGE_AFBEELDING)})
            )
    op.execute(
        foto_table.update().
            where(foto_table.c.fototype==op.inline_literal('G')).
            values({'fotosoort':op.inline_literal(const.OPGRAVINGSFOTO)})
            )
    op.execute(
        foto_table.update().
            where(foto_table.c.fototype==op.inline_literal('H')).
            values({'fotosoort':op.inline_literal(const.OBJECTFOTO)})
            )
    op.execute(
        foto_table.update().
            where(foto_table.c.directory.ilike(op.inline_literal('%h object%'))).
            values({'fotosoort':op.inline_literal(const.OBJECTFOTO)})
            )
    op.execute(
        foto_table.update().
            where(foto_table.c.directory.ilike(op.inline_literal('%velddocument%'))).
            values({'fotosoort':op.inline_literal(const.VELDDOCUMENT)})
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Def_Foto_fotosoort'), table_name='Def_Foto')
    op.drop_column('Def_Foto', 'fotosoort')
    # ### end Alembic commands ###
