"""empty message

Revision ID: 84b2e722a04c
Revises: 30bcd87e1b65
Create Date: 2022-06-08 09:17:13.013798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b2e722a04c'
down_revision = '30bcd87e1b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('aantal_fotos', sa.Integer(), nullable=True))
    op.drop_column('Def_Artefact', 'foto_teller')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('foto_teller', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Def_Artefact', 'aantal_fotos')
    # ### end Alembic commands ###
