"""Langere velden

Revision ID: 8b06f63cb8b5
Revises: 94ce8acedb85
Create Date: 2022-02-25 10:16:40.993477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b06f63cb8b5'
down_revision = '94ce8acedb85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Artefact', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'typecd',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'functievoorwerp',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'artefactsoort',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Doos', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Foto', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageUUID',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageMiddleUUID',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageThumbUUID',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Plaatsing', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Project', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index('idx_Def_Project_location', table_name='Def_Project')
    op.alter_column('Def_Put', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'vlaknr',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Standplaats', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Stelling', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vindplaats', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vlak', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'vlaknr',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('contact', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('contact_group', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('gender', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('observation', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index('idx_observation_location', table_name='observation')
    op.alter_column('person', '_id',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.create_index('idx_observation_location', 'observation', ['location'], unique=False)
    op.alter_column('observation', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('gender', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('contact_group', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('contact', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Vondst', 'vlaknr',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Vondst', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Vlak', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Vindplaats', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Stelling', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Standplaats', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Spoor', 'vlaknr',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Spoor', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Put', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.create_index('idx_Def_Project_location', 'Def_Project', ['location'], unique=False)
    op.alter_column('Def_Project', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Plaatsing', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageThumbUUID',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageMiddleUUID',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Foto', 'imageUUID',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Foto', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Doos', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'artefactsoort',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'functievoorwerp',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'typecd',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Def_Artefact', '_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###
