"""empty message

Revision ID: 8eebd53c40aa
Revises: 4ac016a2b121
Create Date: 2020-03-02 21:17:40.433132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eebd53c40aa'
down_revision = '4ac016a2b121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.drop_index('ix_Def_Foto_artefactID', table_name='Def_Foto')
    op.drop_index('ix_Def_Foto_projectID', table_name='Def_Foto')
    op.drop_table('Def_Foto')
    op.drop_index('idx_observation_location', table_name='observation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_observation_location', 'observation', ['location'], unique=False)
    op.create_table('Def_Foto',
    sa.Column('primary_key', sa.INTEGER(), server_default=sa.text('nextval(\'"Def_Foto_primary_key_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('artefactnr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('directory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fileName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fileSize', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fileType', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fotonr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fotosubnr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fototype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imageID', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('key_artefact', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('key_project', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('key_project_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('key_vondst', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('projectcd', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('putnr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('soort', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('vondstnr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('projectID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artefactID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artefactID'], ['Def_Artefact.primary_key'], name='Def_Foto_artefactID_fkey'),
    sa.ForeignKeyConstraint(['projectID'], ['Def_Project.primary_key'], name='Def_Foto_projectID_fkey'),
    sa.PrimaryKeyConstraint('primary_key', name='Def_Foto_pkey')
    )
    op.create_index('ix_Def_Foto_projectID', 'Def_Foto', ['projectID'], unique=False)
    op.create_index('ix_Def_Foto_artefactID', 'Def_Foto', ['artefactID'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
