"""empty message

Revision ID: 939c3cd078cb
Revises: 034282803550
Create Date: 2020-03-08 20:31:15.215388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939c3cd078cb'
down_revision = '034282803550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('projectID', sa.Integer(), nullable=True))
    op.drop_column('Def_Spoor', 'projectcd')    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('projectcd', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Def_Spoor', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Spoor_projectID'), table_name='Def_Spoor')
    op.drop_column('Def_Spoor', 'projectID')
    # ### end Alembic commands ###
