"""empty message

Revision ID: 94ce8acedb85
Revises: cd524a5dd945
Create Date: 2022-02-16 19:48:53.503557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ce8acedb85'
down_revision = 'cd524a5dd945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('subnr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Artefact', 'subnr')
    # ### end Alembic commands ###
