"""empty message

Revision ID: 954ca660b1cf
Revises: a1ebd3a2cdf4
Create Date: 2020-02-15 07:27:59.771838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954ca660b1cf'
down_revision = 'a1ebd3a2cdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Fotos', sa.Column('photo', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Fotos', 'photo')
    # ### end Alembic commands ###
