"""empty message

Revision ID: 98b443c96065
Revises: 64f6635ac89e
Create Date: 2020-02-26 17:16:07.168839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b443c96065'
down_revision = '64f6635ac89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Fotos', sa.Column('artefactID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Fotos_artefactID'), 'Def_Fotos', ['artefactID'], unique=False)
    op.create_foreign_key(None, 'Def_Fotos', 'Def_Artefact', ['artefactID'], ['primary_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Fotos', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Fotos_artefactID'), table_name='Def_Fotos')
    op.drop_column('Def_Fotos', 'artefactID')
    # ### end Alembic commands ###
