"""empty message

Revision ID: 98b8b99be019
Revises: ed755a0030b4
Create Date: 2020-02-14 20:29:19.277220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98b8b99be019'
down_revision = 'ed755a0030b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Spoor', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('_id', postgresql.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
