"""Bruiklenen toegevoegd

Revision ID: 9fd9f4c51e52
Revises: 7ad8c8efb48f
Create Date: 2022-11-25 07:40:26.165317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd9f4c51e52'
down_revision = '7ad8c8efb48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Def_bruikleen_Partij_bruikleen_id'), 'Def_bruikleen_Partij', ['bruikleen_id'], unique=False)
    op.create_index(op.f('ix_Def_bruikleen_Partij_partij_id'), 'Def_bruikleen_Partij', ['partij_id'], unique=False)
    op.drop_constraint('Def_bruikleen_Partij_bruikleen_id_fkey', 'Def_bruikleen_Partij', type_='foreignkey')
    op.drop_constraint('Def_bruikleen_Partij_partij_id_fkey', 'Def_bruikleen_Partij', type_='foreignkey')
    op.create_foreign_key(None, 'Def_bruikleen_Partij', 'Def_Partij', ['partij_id'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_bruikleen_Partij', 'Def_Bruikleen', ['bruikleen_id'], ['primary_key'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_bruikleen_Partij', type_='foreignkey')
    op.drop_constraint(None, 'Def_bruikleen_Partij', type_='foreignkey')
    op.create_foreign_key('Def_bruikleen_Partij_partij_id_fkey', 'Def_bruikleen_Partij', 'Def_Partij', ['partij_id'], ['primary_key'])
    op.create_foreign_key('Def_bruikleen_Partij_bruikleen_id_fkey', 'Def_bruikleen_Partij', 'Def_Bruikleen', ['bruikleen_id'], ['primary_key'])
    op.drop_index(op.f('ix_Def_bruikleen_Partij_partij_id'), table_name='Def_bruikleen_Partij')
    op.drop_index(op.f('ix_Def_bruikleen_Partij_bruikleen_id'), table_name='Def_bruikleen_Partij')
    # ### end Alembic commands ###
