"""empty message

Revision ID: a1ebd3a2cdf4
Revises: 601ab3bb74f3
Create Date: 2020-02-15 06:57:02.429874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ebd3a2cdf4'
down_revision = '601ab3bb74f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Doos', sa.Column('StellingID', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_Def_Doos_StellingID'), 'Def_Doos', ['StellingID'], unique=False)
    op.create_foreign_key(None, 'Def_Doos', 'Def_Stelling', ['StellingID'], ['primary_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Doos', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Doos_StellingID'), table_name='Def_Doos')
    op.drop_column('Def_Doos', 'StellingID')
    # ### end Alembic commands ###
