"""Indexes toegevoegd

Revision ID: a5ac6828ef6b
Revises: 882e3f1e7dd1
Create Date: 2022-05-16 19:57:30.535883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ac6828ef6b'
down_revision = '882e3f1e7dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_Def_Project_projectnaam', 'Def_Project', ['projectnaam'], unique=False)
    op.create_index('idx_Def_Doos_doosnr', 'Def_Doos', ['doosnr'], unique=False)
    op.create_index('idx_Def_Put_putnr', 'Def_Put', ['putnr'], unique=False)
    op.create_index('idx_Def_Vlak_vlaknr', 'Def_Vlak', ['vlaknr'], unique=False)
    op.create_index('idx_Def_Spoor_spoornr', 'Def_Spoor', ['spoornr'], unique=False)
    op.create_index('idx_Def_Vondst_vondstnr', 'Def_Vondst', ['vondstnr'], unique=False)
    op.create_index('idx_Def_Vulling_vullingnr', 'Def_Vulling', ['vullingnr'], unique=False)
    op.create_index('idx_Def_Artefact_artefactnr', 'Def_Artefact', ['artefactnr'], unique=False)
    op.create_index('idx_Def_Artefact_artefactsoort', 'Def_Artefact', ['artefactsoort'], unique=False)
    op.create_index('idx_Def_Foto_fileName', 'Def_Foto', ['fileName'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_Def_Project_projectnaam', table_name='Def_Project')
    op.drop_index('idx_Def_Doos_doosnr', table_name='Def_Doos')
    op.drop_index('idx_Def_Put_putnr', table_name='Def_Put')
    op.drop_index('idx_Def_Vlak_vlaknr', table_name='Def_Vlak')
    op.drop_index('idx_Def_Spoor_spoornr', table_name='Def_Spoor')
    op.drop_index('idx_Def_Vondst_vondstnr', table_name='Def_Vondst')
    op.drop_index('idx_Def_Vulling_vullingnr', table_name='Def_Vulling')
    op.drop_index('idx_Def_Artefact_artefactnr', table_name='Def_Artefact')
    op.drop_index('idx_Def_Artefact_artefactsoort', table_name='Def_Artefact')
    op.drop_index('idx_Def_Foto_fileName', table_name='Def_Foto')
    # ### end Alembic commands ###
