"""empty message

Revision ID: a7cd560b5c94
Revises: 6687fc145d9e
Create Date: 2020-03-01 20:05:14.120296

"""
from alembic import op
import sqlalchemy as sa
from fab_addon_geoalchemy.models import GeoSQLAInterface, Geometry


# revision identifiers, used by Alembic.
revision = 'a7cd560b5c94'
down_revision = '6687fc145d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    #op.drop_index('idx_Def_Artefact_location', table_name='Def_Artefact')
    op.add_column('Def_Project', sa.Column('location', Geometry(geometry_type='POINT', srid=28992), nullable=True))
    op.create_index('idx_Def_project_location', 'Def_Project', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Project', 'location')
    op.create_index('idx_Def_Project_location', 'Def_Project', ['location'], unique=False)
    # ### end Alembic commands ###
