"""empty message

Revision ID: af5efe595da7
Revises: 334b4b97b356
Create Date: 2020-03-02 21:26:35.780871

"""
from alembic import op
import sqlalchemy as sa
import flask_appbuilder

# revision identifiers, used by Alembic.
revision = 'af5efe595da7'
down_revision = '334b4b97b356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Fotos', sa.Column('photo', flask_appbuilder.models.mixins.ImageColumn(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Fotos', 'photo')
    # ### end Alembic commands ###
