"""Added some columns

Revision ID: b3259e91bb5a
Revises: 0599f76be1ee
Create Date: 2022-02-04 14:15:48.373617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3259e91bb5a'
down_revision = '0599f76be1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('artefactsoort', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Artefact', 'artefactsoort')
    # ### end Alembic commands ###
