"""Fulltext veld toegevoegd

Revision ID: bbac58ef7a37
Revises: 9c01c37016de
Create Date: 2023-02-10 13:16:49.636615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbac58ef7a37'
down_revision = '9c01c37016de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Def_ABR', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Artefact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Bestand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Bruikleen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Doos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Monster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Monster_Botanie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Monster_Schelp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Partij', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Plaatsing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Put', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Spoor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Standplaats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Stelling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Vindplaats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Vlak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Vondst', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('Def_Vulling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ft_search', sa.String(), nullable=True, comment='technisch veld om fulltext zoeken te ondersteunen'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Vulling', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Vondst', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Vlak', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Vindplaats', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Stelling', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Standplaats', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Spoor', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Put', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Plaatsing', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Partij', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Monster_Schelp', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Monster_Botanie', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Monster', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Doos', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Bruikleen', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Bestand', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_Artefact', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    with op.batch_alter_table('Def_ABR', schema=None) as batch_op:
        batch_op.drop_column('ft_search')

    # ### end Alembic commands ###
