"""Column met index

Revision ID: c09f6d00d6a2
Revises: 5f0ea3300ee0
Create Date: 2022-05-18 17:57:47.092241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09f6d00d6a2'
down_revision = '5f0ea3300ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_Def_Artefact_artefactnr', table_name='Def_Artefact')
    op.drop_index('idx_Def_Artefact_artefactsoort', table_name='Def_Artefact')
    op.drop_index('idx_Def_Doos_doosnr', table_name='Def_Doos')
    op.drop_index('idx_Def_Foto_fileName', table_name='Def_Foto')
    op.drop_index('idx_fototype', table_name='Def_Foto')
    op.drop_index('idx_Def_Project_location', table_name='Def_Project')
    op.drop_index('idx_Def_Project_projectnaam', table_name='Def_Project')
    op.drop_index('idx_Def_Put_putnr', table_name='Def_Put')
    op.drop_index('idx_Def_Spoor_spoornr', table_name='Def_Spoor')
    op.drop_index('idx_Def_Vlak_vlaknr', table_name='Def_Vlak')
    op.add_column('Def_Vondst', sa.Column('nieuw', sa.String(length=8), nullable=True))
    op.drop_index('idx_Def_Vondst_vondstnr', table_name='Def_Vondst')
    op.create_index(op.f('ix_Def_Vondst_nieuw'), 'Def_Vondst', ['nieuw'], unique=False)
    op.drop_index('idx_Def_Vulling_vullingnr', table_name='Def_Vulling')
    op.drop_index('idx_observation_location', table_name='observation')
    op.create_index(op.f('ix_Def_Foto_fototype'), 'Def_Foto', ['fototype'], unique=False)

    #op.create_index('ix_observation_location', 'observation', ['location'], unique=False)
    #op.create_index('ix_Def_Vulling_vullingnr', 'Def_Vulling', ['vullingnr'], unique=False)
    #op.create_index('ix_Def_Vondst_vondstnr', 'Def_Vondst', ['vondstnr'], unique=False)
    #op.create_index('ix_Def_Vlak_vlaknr', 'Def_Vlak', ['vlaknr'], unique=False)
    #op.create_index('ix_Def_Spoor_spoornr', 'Def_Spoor', ['spoornr'], unique=False)
    #op.create_index('ix_Def_Put_putnr', 'Def_Put', ['putnr'], unique=False)
    #op.create_index('ix_Def_Project_projectnaam', 'Def_Project', ['projectnaam'], unique=False)
    #op.create_index('ix_Def_Project_location', 'Def_Project', ['location'], unique=False)
    #op.create_index('ix_fototype', 'Def_Foto', ['fototype'], unique=False)
    #op.create_index('ix_Def_Foto_fileName', 'Def_Foto', ['fileName'], unique=False)
    #op.create_index('ix_Def_Doos_doosnr', 'Def_Doos', ['doosnr'], unique=False)
    #op.create_index('ix_Def_Artefact_artefactsoort', 'Def_Artefact', ['artefactsoort'], unique=False)
    #op.create_index('ix_Def_Artefact_artefactnr', 'Def_Artefact', ['artefactnr'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('idx_Def_Artefact_artefactnr', table_name='Def_Artefact')
    #op.drop_index('idx_Def_Artefact_artefactsoort', table_name='Def_Artefact')
    #op.drop_index('idx_Def_Doos_doosnr', table_name='Def_Doos')
    #op.drop_index('idx_Def_Foto_fileName', table_name='Def_Foto')
    #op.drop_index('idx_fototype', table_name='Def_Foto')
    #op.drop_index('idx_Def_Project_location', table_name='Def_Project')
    #op.drop_index('idx_Def_Project_projectnaam', table_name='Def_Project')
    #op.drop_index('idx_Def_Put_putnr', table_name='Def_Put')
    #op.drop_index('idx_Def_Spoor_spoornr', table_name='Def_Spoor')
    #op.drop_index('idx_Def_Vlak_vlaknr', table_name='Def_Vlak')
    #op.drop_index('idx_Def_Vondst_vondstnr', table_name='Def_Vondst')
    #op.drop_index('idx_Def_Vulling_vullingnr', table_name='Def_Vulling')
    #op.drop_index('idx_observation_location', table_name='observation')

    op.create_index('idx_observation_location', 'observation', ['location'], unique=False)
    op.create_index('idx_Def_Vulling_vullingnr', 'Def_Vulling', ['vullingnr'], unique=False)
    op.drop_index(op.f('ix_Def_Vondst_nieuw'), table_name='Def_Vondst')
    op.drop_index(op.f('ix_Def_Foto_fototype'), table_name='Def_Foto')
    op.create_index('idx_Def_Vondst_vondstnr', 'Def_Vondst', ['vondstnr'], unique=False)
    op.drop_column('Def_Vondst', 'nieuw')
    op.create_index('idx_Def_Vlak_vlaknr', 'Def_Vlak', ['vlaknr'], unique=False)
    op.create_index('idx_Def_Spoor_spoornr', 'Def_Spoor', ['spoornr'], unique=False)
    op.create_index('idx_Def_Put_putnr', 'Def_Put', ['putnr'], unique=False)
    op.create_index('idx_Def_Project_projectnaam', 'Def_Project', ['projectnaam'], unique=False)
    op.create_index('idx_Def_Project_location', 'Def_Project', ['location'], unique=False)
    op.create_index('idx_fototype', 'Def_Foto', ['fototype'], unique=False)
    op.create_index('idx_Def_Foto_fileName', 'Def_Foto', ['fileName'], unique=False)
    op.create_index('idx_Def_Doos_doosnr', 'Def_Doos', ['doosnr'], unique=False)
    op.create_index('idx_Def_Artefact_artefactsoort', 'Def_Artefact', ['artefactsoort'], unique=False)
    op.create_index('idx_Def_Artefact_artefactnr', 'Def_Artefact', ['artefactnr'], unique=False)

    # ### end Alembic commands ###
