"""empty message

Revision ID: c12bc4245027
Revises: 00c0531fda64
Create Date: 2020-03-09 21:50:14.335067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12bc4245027'
down_revision = '00c0531fda64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('putID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Spoor_putID'), 'Def_Spoor', ['putID'], unique=False)
    op.create_foreign_key(None, 'Def_Spoor', 'Def_Put', ['putID'], ['primary_key'])
    op.drop_column('Def_Spoor', 'putnr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('putnr', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Def_Spoor', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Spoor_putID'), table_name='Def_Spoor')
    op.drop_column('Def_Spoor', 'putID')
    # ### end Alembic commands ###
