"""Test Standplaats verwijderd

Revision ID: c1d619060bc6
Revises: feb4ef4c0dfb
Create Date: 2022-02-04 13:27:32.857801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d619060bc6'
down_revision = 'feb4ef4c0dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Standplaats', 'testcol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Standplaats', sa.Column('testcol', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
