"""String len to 1024

Revision ID: cb29a961647c
Revises: 0a820a0733d2
Create Date: 2022-03-11 08:37:07.596605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb29a961647c'
down_revision = '0a820a0733d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Artefact', 'materiaalsoort',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=True)
    op.drop_index('idx_Def_Project_location', table_name='Def_Project')
    op.drop_index('idx_observation_location', table_name='observation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_observation_location', 'observation', ['location'], unique=False)
    op.create_index('idx_Def_Project_location', 'Def_Project', ['location'], unique=False)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'materiaalsoort',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
