"""Vlak verbeterd 2

Revision ID: cd524a5dd945
Revises: 9f6a2bf86ef3
Create Date: 2022-02-16 15:39:14.033247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd524a5dd945'
down_revision = '9f6a2bf86ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vlak', sa.Column('projectID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Vlak_projectID'), 'Def_Vlak', ['projectID'], unique=False)
    op.create_foreign_key(None, 'Def_Vlak', 'Def_Project', ['projectID'], ['primary_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Vlak', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Vlak_projectID'), table_name='Def_Vlak')
    op.drop_column('Def_Vlak', 'projectID')
    # ### end Alembic commands ###
