"""empty message

Revision ID: cec4fd4df2f5
Revises: b237a08adb3b
Create Date: 2020-03-09 20:45:26.899914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec4fd4df2f5'
down_revision = 'b237a08adb3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('key_put', sa.String(length=40), nullable=True))
    op.add_column('Def_Spoor', sa.Column('key_spoor', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Spoor', 'key_spoor')
    op.drop_column('Def_Spoor', 'key_put')
    # ### end Alembic commands ###
