"""Bruiklenen toegevoegd 3

Revision ID: cf658131cb2f
Revises: 21f7e9b99149
Create Date: 2022-11-25 07:52:48.570851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf658131cb2f'
down_revision = '21f7e9b99149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Def_bruikleen_Partij_bruikleen_id', table_name='Def_bruikleen_Partij')
    op.drop_index('ix_Def_bruikleen_Partij_partij_id', table_name='Def_bruikleen_Partij')
    op.drop_table('Def_bruikleen_Partij')
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment='',
               existing_nullable=True)
    op.add_column('Def_Bruikleen', sa.Column('partijID', sa.Integer(), nullable=False))
    op.alter_column('Def_Bruikleen', 'datum_uitgeleend',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_Def_Bruikleen_partijID'), 'Def_Bruikleen', ['partijID'], unique=False)
    op.create_foreign_key(None, 'Def_Bruikleen', 'Def_Partij', ['partijID'], ['primary_key'], deferrable=True)
    op.alter_column('Def_Partij', 'naam',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Partij', 'naam',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_constraint(None, 'Def_Bruikleen', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Bruikleen_partijID'), table_name='Def_Bruikleen')
    op.alter_column('Def_Bruikleen', 'datum_uitgeleend',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('Def_Bruikleen', 'partijID')
    op.alter_column('Def_Artefact', 'wervelkolom',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'skeletelementen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'secundair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'schedel',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'rechterarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'primair_graf',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerbeen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'linkerarm',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'kist_waargenomen',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_lumc',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'doos_delft',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'handgevormd',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'gedraaid',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'percentage',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('Def_Artefact', 'max_diameter',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.create_table('Def_bruikleen_Partij',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Def_bruikleen_Partij_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('bruikleen_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partij_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bruikleen_id'], ['Def_Bruikleen.primary_key'], name='Def_bruikleen_Partij_bruikleen_id_fkey', deferrable=True),
    sa.ForeignKeyConstraint(['partij_id'], ['Def_Partij.primary_key'], name='Def_bruikleen_Partij_partij_id_fkey', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='Def_bruikleen_Partij_pkey')
    )
    op.create_index('ix_Def_bruikleen_Partij_partij_id', 'Def_bruikleen_Partij', ['partij_id'], unique=False)
    op.create_index('ix_Def_bruikleen_Partij_bruikleen_id', 'Def_bruikleen_Partij', ['bruikleen_id'], unique=False)
    # ### end Alembic commands ###
