"""empty message

Revision ID: d315f9fc15c2
Revises: 98b443c96065
Create Date: 2020-02-28 20:41:10.266601

"""
from alembic import op
import sqlalchemy as sa
from fab_addon_geoalchemy.models import GeoSQLAInterface, Geometry


# revision identifiers, used by Alembic.
revision = 'd315f9fc15c2'
down_revision = '98b443c96065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ### geoalchemy2.types.
    op.add_column('Def_Artefact', sa.Column('location', Geometry(geometry_type='POINT', srid=4326), nullable=True))
    op.add_column('Def_Spoor', sa.Column('vlaknr', sa.String(length=40), nullable=True))
    op.drop_column('Def_Spoor', 'vlakker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('vlakker', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('Def_Spoor', 'vlaknr')
    op.drop_column('Def_Artefact', 'location')
    # ### end Alembic commands ###
