"""empty message

Revision ID: db02a2699d17
Revises: bbaa7809819e
Create Date: 2020-02-15 06:13:41.214516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db02a2699d17'
down_revision = 'bbaa7809819e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Doos', sa.Column('ArtefactID', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_Def_Doos_ArtefactID'), 'Def_Doos', ['ArtefactID'], unique=False)
    op.create_foreign_key(None, 'Def_Doos', 'Def_Artefact', ['ArtefactID'], ['primary_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Doos', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Doos_ArtefactID'), table_name='Def_Doos')
    op.drop_column('Def_Doos', 'ArtefactID')
    # ### end Alembic commands ###
