"""Spoor verbeterd

Revision ID: dcaccb245057
Revises: 0688497336ab
Create Date: 2022-02-16 14:24:34.782696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcaccb245057'
down_revision = '0688497336ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Spoor', sa.Column('breedte_bovenkant', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('lengte_bovenkant', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('hoogte_bovenkant', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('hoogte_onderkant', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('profiel', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('richting', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('steenformaat', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('metselverband', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('jonger_dan', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('ouder_dan', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('sporen_zelfde_periode', sa.String(length=200), nullable=True))
    op.add_column('Def_Spoor', sa.Column('vlakID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Spoor_vlakID'), 'Def_Spoor', ['vlakID'], unique=False)
    op.drop_constraint('Def_Spoor_projectID_fkey', 'Def_Spoor', type_='foreignkey')
    op.drop_constraint('Def_Spoor_putID_fkey', 'Def_Spoor', type_='foreignkey')
    op.create_foreign_key(None, 'Def_Spoor', 'Def_Project', ['projectID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Spoor', 'Def_Vlak', ['vlakID'], ['primary_key'], deferrable=True)
    op.create_foreign_key(None, 'Def_Spoor', 'Def_Put', ['putID'], ['primary_key'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Spoor', type_='foreignkey')
    op.drop_constraint(None, 'Def_Spoor', type_='foreignkey')
    op.drop_constraint(None, 'Def_Spoor', type_='foreignkey')
    op.create_foreign_key('Def_Spoor_putID_fkey', 'Def_Spoor', 'Def_Put', ['putID'], ['primary_key'])
    op.create_foreign_key('Def_Spoor_projectID_fkey', 'Def_Spoor', 'Def_Project', ['projectID'], ['primary_key'])
    op.drop_index(op.f('ix_Def_Spoor_vlakID'), table_name='Def_Spoor')
    op.drop_column('Def_Spoor', 'vlakID')
    op.drop_column('Def_Spoor', 'sporen_zelfde_periode')
    op.drop_column('Def_Spoor', 'ouder_dan')
    op.drop_column('Def_Spoor', 'jonger_dan')
    op.drop_column('Def_Spoor', 'metselverband')
    op.drop_column('Def_Spoor', 'steenformaat')
    op.drop_column('Def_Spoor', 'richting')
    op.drop_column('Def_Spoor', 'profiel')
    op.drop_column('Def_Spoor', 'hoogte_onderkant')
    op.drop_column('Def_Spoor', 'hoogte_bovenkant')
    op.drop_column('Def_Spoor', 'lengte_bovenkant')
    op.drop_column('Def_Spoor', 'breedte_bovenkant')
    # ### end Alembic commands ###
