"""empty message

Revision ID: e18e341cd2fb
Revises: e21cf3a3ae36
Create Date: 2020-03-09 21:10:26.382988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18e341cd2fb'
down_revision = 'e21cf3a3ae36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Artefact', sa.Column('vondstID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Artefact_vondstID'), 'Def_Artefact', ['vondstID'], unique=False)
    op.create_foreign_key(None, 'Def_Artefact', 'Def_Vondst', ['vondstID'], ['primary_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Artefact', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Artefact_vondstID'), table_name='Def_Artefact')
    op.drop_column('Def_Artefact', 'vondstID')
    # ### end Alembic commands ###
