"""empty message

Revision ID: e21cf3a3ae36
Revises: cec4fd4df2f5
Create Date: 2020-03-09 20:59:55.959268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21cf3a3ae36'
down_revision = 'cec4fd4df2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Def_Project', '_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('Def_Project', 'projectcd',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.create_unique_constraint(None, 'Def_Project', ['_id'])
    op.create_unique_constraint(None, 'Def_Project', ['projectcd'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Project', type_='unique')
    op.drop_constraint(None, 'Def_Project', type_='unique')
    op.alter_column('Def_Project', 'projectcd',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('Def_Project', '_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
