"""Overbodige velden verwijderd

Revision ID: e7a45c0787e0
Revises: f8da9718497b
Create Date: 2022-02-04 13:55:03.419727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a45c0787e0'
down_revision = 'f8da9718497b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Put', sa.Column('_id', sa.String(length=40), nullable=True))
    op.add_column('Def_Spoor', sa.Column('_id', sa.String(length=40), nullable=True))
    op.drop_column('Def_Vindplaats', 'table')
    op.alter_column('Def_Vondst', '_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_constraint('Def_Vondst__id_key', 'Def_Vondst', type_='unique')
    op.add_column('contact', sa.Column('_id', sa.String(length=40), nullable=True))
    op.add_column('contact_group', sa.Column('_id', sa.String(length=40), nullable=True))
    op.add_column('gender', sa.Column('_id', sa.String(length=40), nullable=True))
    op.add_column('observation', sa.Column('_id', sa.String(length=40), nullable=True))
    op.add_column('person', sa.Column('_id', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', '_id')
    op.drop_column('observation', '_id')
    op.drop_column('gender', '_id')
    op.drop_column('contact_group', '_id')
    op.drop_column('contact', '_id')
    op.create_unique_constraint('Def_Vondst__id_key', 'Def_Vondst', ['_id'])
    op.alter_column('Def_Vondst', '_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.add_column('Def_Vindplaats', sa.Column('table', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('Def_Spoor', '_id')
    op.drop_column('Def_Put', '_id')
    # ### end Alembic commands ###
