"""Monstervelden spoor toegevoegd

Revision ID: ebd00e8bee9f
Revises: 61ad57846915
Create Date: 2022-08-19 14:31:02.757047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd00e8bee9f'
down_revision = '61ad57846915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Monster', sa.Column('spoorID', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Def_Monster_spoorID'), 'Def_Monster', ['spoorID'], unique=False)
    op.create_foreign_key(None, 'Def_Monster', 'Def_Spoor', ['spoorID'], ['primary_key'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Def_Monster', type_='foreignkey')
    op.drop_index(op.f('ix_Def_Monster_spoorID'), table_name='Def_Monster')
    op.drop_column('Def_Monster', 'spoorID')
    # ### end Alembic commands ###
