"""Opmerkingen bij vondst

Revision ID: ecb87b1cae69
Revises: 178dc966877a
Create Date: 2022-05-05 10:47:19.472413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb87b1cae69'
down_revision = '178dc966877a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vondst', sa.Column('opmerkingen', sa.String(length=1024), nullable=True))
    op.drop_column('Def_Vondst', 'inhoud')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Vondst', sa.Column('inhoud', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('Def_Vondst', 'opmerkingen')
    # ### end Alembic commands ###
