"""Hernoemen entiteiten

Revision ID: ee68b4b6e95f
Revises: d1b316147b14
Create Date: 2022-05-04 14:47:38.692280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee68b4b6e95f'
down_revision = 'd1b316147b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE  "Def_Artefact" ALTER COLUMN artefactsoort TYPE VARCHAR(255);

        DROP TYPE IF EXISTS discrartefactsoortenum;

        CREATE TYPE discrartefactsoortenum AS ENUM 
            ('Aardewerk', 'Dierlijk_Bot', 'Glas', 'Hout', 'Keramiek', 'Kleipijp', 'Leer', 'Menselijk_Bot', 'Metaal', 'Munt', 'Onbekend', 'Schelp', 'Steen', 'Textiel', 'Bouwaardewerk');

        ALTER TABLE "Def_Artefact" ALTER COLUMN artefactsoort TYPE discrartefactsoortenum 
            USING (artefactsoort::discrartefactsoortenum);
        '''
    )


def downgrade():
    op.execute(
        '''
        ALTER TABLE  "Def_Artefact" ALTER COLUMN artefactsoort TYPE VARCHAR(255);

        DROP TYPE IF EXISTS discrartefactsoortenum;

        CREATE TYPE discrartefactsoortenum AS ENUM 
            ('Aardewerk', 'Bot', 'Glas', 'Hout', 'Keramiek', 'Kleipijp', 'Leer', 'Menselijk_Materiaal', 'Metaal', 'Munt', 'Spijker', 'Onbekend', 'Schelp', 'Steen', 'Textiel', 'Ivoor', 'Hoorn');

        ALTER TABLE "Def_Artefact" ALTER COLUMN artefactsoort TYPE discrartefactsoortenum 
            USING (artefactsoort::discrartefactsoortenum);
        '''
    )


