"""ABR-coderig toegevoegd

Revision ID: f5e2d9e9c13e
Revises: 96ff57201929
Create Date: 2022-10-22 14:24:01.534678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e2d9e9c13e'
down_revision = '96ff57201929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Def_Foto_putID', table_name='Def_Foto')
    op.drop_index('ix_Def_Foto_spoorID', table_name='Def_Foto')
    op.drop_index('ix_Def_Foto_vondstID', table_name='Def_Foto')
    op.drop_constraint('Def_Foto_putID_fkey', 'Def_Foto', type_='foreignkey')
    op.drop_constraint('Def_Foto_vondstID_fkey', 'Def_Foto', type_='foreignkey')
    op.drop_constraint('Def_Foto_spoorID_fkey', 'Def_Foto', type_='foreignkey')
    op.drop_column('Def_Foto', 'vondstID')
    op.drop_column('Def_Foto', 'putID')
    op.drop_column('Def_Foto', 'spoorID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Foto', sa.Column('spoorID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Def_Foto', sa.Column('putID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Def_Foto', sa.Column('vondstID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Def_Foto_spoorID_fkey', 'Def_Foto', 'Def_Spoor', ['spoorID'], ['primary_key'], deferrable=True)
    op.create_foreign_key('Def_Foto_vondstID_fkey', 'Def_Foto', 'Def_Vondst', ['vondstID'], ['primary_key'], deferrable=True)
    op.create_foreign_key('Def_Foto_putID_fkey', 'Def_Foto', 'Def_Put', ['putID'], ['primary_key'], deferrable=True)
    op.create_index('ix_Def_Foto_vondstID', 'Def_Foto', ['vondstID'], unique=False)
    op.create_index('ix_Def_Foto_spoorID', 'Def_Foto', ['spoorID'], unique=False)
    op.create_index('ix_Def_Foto_putID', 'Def_Foto', ['putID'], unique=False)
    # ### end Alembic commands ###
