"""Generiek Wasstraatmodel 

Revision ID: f8da9718497b
Revises: 65945461f8da
Create Date: 2022-02-04 13:48:12.633508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8da9718497b'
down_revision = '65945461f8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Def_Doos', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('Def_Doos', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('Def_Doos', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('Def_Foto', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('Def_Foto', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('Def_Plaatsing', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('Def_Plaatsing', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('Def_Put', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('Def_Put', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('Def_Put', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('Def_Spoor', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('Def_Spoor', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('Def_Standplaats', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('Def_Standplaats', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('Def_Standplaats', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('Def_Vindplaats', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('Def_Vlak', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('Def_Vlak', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('Def_Vlak', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('Def_Vondst', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('contact', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('contact', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('contact', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('contact_group', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('contact_group', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('contact_group', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('gender', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('gender', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('gender', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('observation', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('observation', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('observation', sa.Column('brondata', sa.Text(), nullable=True))
    op.add_column('person', sa.Column('herkomst', sa.Text(), nullable=True))
    op.add_column('person', sa.Column('soort', sa.String(length=80), nullable=True))
    op.add_column('person', sa.Column('brondata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'brondata')
    op.drop_column('person', 'soort')
    op.drop_column('person', 'herkomst')
    op.drop_column('observation', 'brondata')
    op.drop_column('observation', 'soort')
    op.drop_column('observation', 'herkomst')
    op.drop_column('gender', 'brondata')
    op.drop_column('gender', 'soort')
    op.drop_column('gender', 'herkomst')
    op.drop_column('contact_group', 'brondata')
    op.drop_column('contact_group', 'soort')
    op.drop_column('contact_group', 'herkomst')
    op.drop_column('contact', 'brondata')
    op.drop_column('contact', 'soort')
    op.drop_column('contact', 'herkomst')
    op.drop_column('Def_Vondst', 'soort')
    op.drop_column('Def_Vlak', 'brondata')
    op.drop_column('Def_Vlak', 'soort')
    op.drop_column('Def_Vlak', 'herkomst')
    op.drop_column('Def_Vindplaats', 'herkomst')
    op.drop_column('Def_Standplaats', 'brondata')
    op.drop_column('Def_Standplaats', 'soort')
    op.drop_column('Def_Standplaats', 'herkomst')
    op.drop_column('Def_Spoor', 'brondata')
    op.drop_column('Def_Spoor', 'soort')
    op.drop_column('Def_Spoor', 'herkomst')
    op.drop_column('Def_Put', 'brondata')
    op.drop_column('Def_Put', 'soort')
    op.drop_column('Def_Put', 'herkomst')
    op.drop_column('Def_Plaatsing', 'soort')
    op.drop_column('Def_Plaatsing', 'herkomst')
    op.drop_column('Def_Foto', 'brondata')
    op.drop_column('Def_Foto', 'herkomst')
    op.drop_column('Def_Doos', 'brondata')
    op.drop_column('Def_Doos', 'soort')
    op.drop_column('Def_Doos', 'herkomst')
    # ### end Alembic commands ###
