"""Test

Revision ID: feb4ef4c0dfb
Revises: ae2459703dc1
Create Date: 2022-02-04 13:25:02.807214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb4ef4c0dfb'
down_revision = 'ae2459703dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Def_Standplaatsss')
    op.add_column('Def_Standplaats', sa.Column('testcol', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Def_Standplaats', 'testcol')
    op.create_table('Def_Standplaatsss',
    sa.Column('primary_key', sa.INTEGER(), server_default=sa.text('nextval(\'"Def_Standplaatsss_primary_key_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('doosnr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('primary_key', name='Def_Standplaatsss_pkey')
    )
    # ### end Alembic commands ###
