services:
  postgres:
    container_name: "wasstraat_postgres"
    image: wasstraat_postgres
    env_file:
       - ./config/postgres.env
       - ./config/flask.env
    ports:
      - "5432:5432"
    volumes:
      - wasstraat_postgres_volume:/var/lib/postgresql/data
      - ./data/backup/postgres:/backup
    build:
      dockerfile: ./services/postgres/Dockerfile
      context: .
    restart: unless-stopped

  airflow:
    container_name: "wasstraat_airflow"
    image: wasstraat_airflow
    env_file:
       - ./config/airflow.env
       - ./config/airflow_db.env
       - ./config/mongo.env
       - ./config/postgres.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
      - elasticsearch
    volumes:
      # Production settings
      # - ./data/input/projecten:/input/projecten
      # - ./data/input/images:/input/images
      # Testing settings
       - ./data/input/projecten:/input/projecten
       - ./data/input/images:/input/images
       - ./data/input/rapporten:/input/rapporten
       - ./data/input/monsterdatabase:/input/monsterdatabase
       - ./data/input/Delf-IT:/input/delfits
       - ./data/input/magazijnlijst:/input/magazijnlijst
       - ./data/input/digifotos:/input/digifotos
       - ./data/input/referentietabellen:/input/referentietabellen
       - ./data/output/archeomedia:/output/archeomedia
       - ./airflow_app/dags:/opt/airflow/dags
       - ./airflow_app/scripts:/opt/airflow/scripts
       - ./airflow_app/.vscode:/opt/airflow/.vscode
       - ./data/wasstraat_config:/opt/airflow/config
       - ./shared:/opt/airflow/dags/shared/
    build:
      dockerfile: ./services/airflow/Dockerfile
      context: .

  redis:
    image: redis:7.2-alpine
    container_name: "wasstraat_redis"
    ports:
      - '6379:6379'
    env_file:
      - ./config/redis.env
    command: >
      sh -c "redis-server --requirepass $$REDIS_PASSWORD"


# Computation
  flask:
    container_name: "wasstraat_flask"
    image: wasstraat_flask
    build:
      dockerfile: ./services/flask/Dockerfile
      context: .
    env_file:
      - ./config/flask.env
      - ./config/postgres.env
      - ./config/mongo.env
      - ./config/redis.env
    ports:
      - '5051:5051'
    depends_on:
      - postgres
      - mongo
      - redis
      - elasticsearch
      - apache
    volumes:
      - ./data/output/archeomedia:/output/archeomedia


  mongo:
    image: mongo:7.0
    container_name: "wasstraat_mongo"
    ports:
      - '27017:27017'
    env_file:
      - ./config/mongo.env
    volumes:
      - wasstraat_mongo_volume:/data/db
      - wasstraat_mongo_config_volume:/data/configdb
      - ./data/backup/mongo:/backup
    restart: unless-stopped

  jupyter:
    container_name: wasstraat_jupyter
    build:
      dockerfile: ./services/jupyter/Dockerfile
      context: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/
      - ./data/wasstraat_config:/home/jovyan/wasstraat_config/
      - ./airflow_app/dags:/opt/wasstraat/
      - ./shared:/home/jovyan/shared/
      - ./data/input:/home/jovyan/basefiles
      - ./data/input/images:/input/images
      - ./data/input/referentietabellen:/input/referentietabellen
      - ./data/output/archeomedia:/output/archeomedia
      # - ./data/input:/input/sdschijf
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    env_file:
       - ./config/airflow.env
       - ./config/airflow_db.env
       - ./config/mongo.env
       - ./config/postgres.env

  apache:
    container_name: wasstraat_apache
    build:
      dockerfile: ./services/apache/Dockerfile
      context: .
    volumes:
      - ./data/output:/usr/local/apache2/htdocs
    ports:
      - '5052:5052'


# docker pull docker.elastic.co/elasticsearch/elasticsearch:8.17.0
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: wasstraat_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS= -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300


volumes:
    wasstraat_postgres_volume:
    wasstraat_mongo_volume:
    wasstraat_mongo_config_volume:
    elasticsearch-data:
      #driver: local
