# docker-compose.example.yml
# Override voor lokale ontwikkeling met hot-reload van de Flask app.
# Gebruik: make example
services:
  flask:
    environment:
      - env=dev
      - FLASK_DEBUG=1
    build:
      dockerfile: ./services/flask/Dockerfile
      context: .
    image: wasstraat_flask
    volumes:
      - ./app:/app
      - ./shared:/app/app/shared/
