version: "3"

# All available services
services:
  flask:
    environment: 
      - env=prod
      - FLASK_DEBUG=1
      - FLASK_APP=app/app.py
      - PORT=5000
    ports:
      - 5000:5000
    build: 
      dockerfile: ./services/flask/Dockerfile-meinheld
      context: .
    image: wasstraat_flask_meinheld
    volumes:
      #- ./examples/polymorph:/app
      #- ./data/images:/images
      - ./app:/app
      - ./shared:/app/app/shared/
      # ../Flask-AppBuilder/examples/employees:/app

