# All available services
services:
  airflow:
    ports:
      - "8080:8080"   # bestaande webinterface
      - "5678:5678"   # debugpoort
    command: >
      python -m debugpy
      --listen 0.0.0.0:5678
      -m airflow webserver

  flask:
    entrypoint: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    environment: 
      - FLASK_APP=app/app.py
      - env=dev
      - FLASK_DEBUG=1
    build: 
      dockerfile: ./services/flask/Dockerfile
      context: .
    image: wasstraat_flask

    volumes:
      #- ./examples/polymorph:/app
      #- ./data/images:/images
      - ./app:/app
      - ./shared:/app/app/shared/

   