# All available services
services:
  airflow:
    environment:
      # Debug (zoals je nu hebt)
      - DEBUGPY=1
      - DEBUG_TARGET=scheduler
      # --- Scheduler/DAG-parser single process ---
      - AIRFLOW__SCHEDULER__DAG_FILE_PROCESSOR_PROCESSES=1  # 1 parser-proces
      # --- Geen parallelle tasks ---
      - AIRFLOW__CORE__PARALLELISM=1           # max aantal gelijktijdige tasks in hele installatie
      - AIRFLOW__CORE__DAG_CONCURRENCY=1       # max gelijktijdige tasks per DAG
      - AIRFLOW__SCHEDULER__MAX_TIS_PER_QUERY=1
    ports:
      - "8080:8080"                # web UI
      - "5678:5678"                # debugpy
      
  flask:
    entrypoint: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    environment: 
      - FLASK_APP=app/app.py
      - env=dev
      - FLASK_DEBUG=1
    build: 
      dockerfile: ./services/flask/Dockerfile
      context: .
    image: wasstraat_flask

    volumes:
      #- ./examples/polymorph:/app
      #- ./data/images:/images
      - ./app:/app
      - ./shared:/app/app/shared/

   