FROM tiangolo/meinheld-gunicorn-flask:python3.8

RUN apt-get update && apt-get -y upgrade && apt-get clean
RUN pip install --upgrade --no-cache-dir pip
RUN pip install --no-cache-dir redis flask_caching flask_dropzone python-magic geopandas pandas numpy folium flask-appbuilder Pillow Flask-Migrate psycopg2-binary pymongo sqlacodegen flask_debugtoolbar pandas_datareader geoalchemy2 typing_extensions

# Fix for Github: https://github.com/tiangolo/meinheld-gunicorn-docker/issues/22 Error: class uri 'egg:meinheld#gunicorn_worker' invalid or not found #22
RUN pip install  --no-cache-dir greenlet==0.4.16

WORKDIR /app/
COPY ./app /app

ENV STATIC_PATH /app/app/static
ENV STATIC_INDEX 1

EXPOSE 5000
