FROM tiangolo/meinheld-gunicorn-flask:python3.8

RUN apt-get update && apt-get -y upgrade && apt-get clean && apt-get install -y poppler-utils
RUN pip install --upgrade --no-cache-dir pip
COPY ./services/flask/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Fix for Github: https://github.com/tiangolo/meinheld-gunicorn-docker/issues/22 Error: class uri 'egg:meinheld#gunicorn_worker' invalid or not found #22
RUN pip install  --no-cache-dir greenlet==0.4.16

WORKDIR /app/
COPY ./app /app
COPY ./shared /app/app/shared

ENV STATIC_PATH /app/app/static
ENV STATIC_INDEX 1

EXPOSE 5000
