\set FLASK_PGUSER `echo "$FLASK_PGUSER"`
\set FLASK_PGPASSWORD `echo "$FLASK_PGPASSWORD"`
\set FLASK_PGDATABASE `echo "$FLASK_PGDATABASE"`


CREATE TABLE airflow__extra_conf(
  conf_name  VARCHAR (255) PRIMARY KEY,
  conf_value VARCHAR (255) NOT NULL
);

CREATE USER :FLASK_PGUSER WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    PASSWORD :'FLASK_PGPASSWORD';

CREATE DATABASE :FLASK_PGDATABASE OWNER :FLASK_PGUSER;
GRANT ALL PRIVILEGES ON DATABASE flask TO flask;

\c flask
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_raster;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION postgis_sfcgal;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION address_standardizer;
CREATE EXTENSION address_standardizer_data_us;
CREATE EXTENSION postgis_tiger_geocoder;